# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Wed Apr 21 03:42:08 2010

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class BSSS(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: BSSS.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, -1)
        self.label_1 = wx.StaticText(self, -1, "Select energy")
        self.text_ctrl_1 = getTextE(self, -1, "")
        self.unit = wx.StaticText(self, -1, "[keV]")
        self.changeEnergy = ChangeE(self, -1, "Change")
        self.label_2 = wx.StaticText(self.panel_1, -1, "Tuning dtheta1")
        self.dtheta_tune = Dtheta(self, -1, "Tune")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_TEXT_ENTER, self.getTextEnergy, self.text_ctrl_1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: BSSS.__set_properties
        self.SetTitle("frame_3")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: BSSS.__do_layout
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7.Add(self.label_1, 0, 0, 0)
        sizer_7.Add(self.text_ctrl_1, 0, 0, 0)
        sizer_7.Add(self.unit, 0, 0, 0)
        sizer_5.Add(sizer_7, 1, wx.EXPAND, 0)
        sizer_5.Add(self.changeEnergy, 0, 0, 0)
        sizer_8.Add(self.label_2, 0, 0, 0)
        self.panel_1.SetSizer(sizer_8)
        sizer_5.Add(self.panel_1, 1, wx.EXPAND, 0)
        sizer_5.Add(self.dtheta_tune, 0, 0, 0)
        self.SetSizer(sizer_5)
        sizer_5.Fit(self)
        self.Layout()
        # end wxGlade

    def getTextEnergy(self, event): # wxGlade: BSSS.<event_handler>
	self.energy_value=float(self.getTextEnergy.GetValue())
	print self.energy_value

# end of class BSSS


