#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue May 25 19:55:05 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class Centeringer(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Centeringer.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.notebook_1 = wx.Notebook(self, -1, style=0)
        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, -1)
        self.leftButton = wx.Button(self.notebook_1_pane_1, -1, "Left")
        self.pintPlusButton = wx.Button(self.notebook_1_pane_1, -1, "+ pint")
        self.upperButton = wx.Button(self.notebook_1_pane_1, -1, "Up")
        self.centerCombo = wx.ComboBox(self.notebook_1_pane_1, -1, choices=["1000", "500", "200", "100", "50", "20", "10", "5", "1", "0.5"], style=wx.CB_DROPDOWN)
        self.label_1 = wx.StaticText(self.notebook_1_pane_1, -1, "[um]", style=wx.ALIGN_CENTRE)
        self.downButton = wx.Button(self.notebook_1_pane_1, -1, "Down")
        self.pintCombo = wx.ComboBox(self.notebook_1_pane_1, -1, choices=["1000", "500", "200", "100", "50", "20", "10", "5", "1", "0.5"], style=wx.CB_DROPDOWN)
        self.label_1_copy = wx.StaticText(self.notebook_1_pane_1, -1, "[um]", style=wx.ALIGN_CENTRE)
        self.rightButton = wx.Button(self.notebook_1_pane_1, -1, "Right")
        self.pintMinusButton = wx.Button(self.notebook_1_pane_1, -1, "- pint")
        self.label_7 = wx.StaticText(self.notebook_1_pane_1, -1, "Zoom")
        self.button_4 = wx.Button(self.notebook_1_pane_1, -1, "IN")
        self.button_4_copy = wx.Button(self.notebook_1_pane_1, -1, "OUT")
        self.button_4_copy_copy = wx.Button(self.notebook_1_pane_1, -1, "STOP")
        self.label_4_copy = wx.StaticText(self.notebook_1_pane_1, -1, "current")
        self.dispPhi_copy = wx.TextCtrl(self.notebook_1_pane_1, -1, "", style=wx.TE_READONLY)
        self.label_8 = wx.StaticText(self.notebook_1_pane_1, -1, "[pulse]")
        self.rotateCCW2 = wx.Button(self.notebook_1_pane_1, -1, "++")
        self.leftButton_copy_copy = wx.Button(self.notebook_1_pane_1, -1, "+")
        self.phiCombo = wx.ComboBox(self.notebook_1_pane_1, -1, choices=["30", "45", "90", "180"], style=wx.CB_DROPDOWN)
        self.label_1_copy_1 = wx.StaticText(self.notebook_1_pane_1, -1, "[deg.]", style=wx.ALIGN_CENTRE)
        self.leftButton_copy_copy_1 = wx.Button(self.notebook_1_pane_1, -1, "-")
        self.leftButton_copy_copy_copy_1 = wx.Button(self.notebook_1_pane_1, -1, "--")
        self.label_4 = wx.StaticText(self.notebook_1_pane_1, -1, "current PHI")
        self.dispPhi = wx.TextCtrl(self.notebook_1_pane_1, -1, "", style=wx.TE_READONLY)
        self.label_5 = wx.StaticText(self.notebook_1_pane_1, -1, "[deg.]")
        self.button_1 = wx.Button(self.notebook_1_pane_1, -1, "Reverse(+)")
        self.button_1_copy = wx.Button(self.notebook_1_pane_1, -1, "Reverse(-)")
        self.label111 = wx.StaticText(self, -1, "Current status")
        self.label_2 = wx.StaticText(self, -1, "gonio x")
        self.dispGonioX = wx.TextCtrl(self, -1, "", style=wx.TE_READONLY)
        self.label_3 = wx.StaticText(self, -1, "[mm]")
        self.button_2 = wx.Button(self, -1, "Update")
        self.label_2_copy = wx.StaticText(self, -1, "gonio y")
        self.dispGonioY = wx.TextCtrl(self, -1, "", style=wx.TE_READONLY)
        self.label_3_copy = wx.StaticText(self, -1, "[mm]")
        self.label_6 = wx.StaticText(self, -1, "Back Light", style=wx.ALIGN_CENTRE)
        self.label_6_copy = wx.StaticText(self, -1, "Collimator", style=wx.ALIGN_CENTRE)
        self.label_6_copy_1 = wx.StaticText(self, -1, "Beam Stopper", style=wx.ALIGN_CENTRE)
        self.label_2_copy_1 = wx.StaticText(self, -1, "gonio z")
        self.dispGonioZ = wx.TextCtrl(self, -1, "", style=wx.TE_READONLY)
        self.label_3_copy_1 = wx.StaticText(self, -1, "[mm]")
        self.onLight = wx.Button(self, -1, "ON")
        self.onLight_copy = wx.Button(self, -1, "ON")
        self.onLight_copy_1 = wx.Button(self, -1, "ON")
        self.label_2_copy_2 = wx.StaticText(self, -1, "gonio zz")
        self.dispGonioZZ = wx.TextCtrl(self, -1, "", style=wx.TE_READONLY)
        self.label_3_copy_2 = wx.StaticText(self, -1, "[mm]")
        self.offLight = wx.Button(self, -1, "OFF")
        self.offLight_copy = wx.Button(self, -1, "OFF")
        self.offLight_copy_1 = wx.Button(self, -1, "OFF")
        self.button_3 = wx.Button(self, -1, "All evacuate")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.pushLeft, self.leftButton)
        self.Bind(wx.EVT_BUTTON, self.pushPpint, self.pintPlusButton)
        self.Bind(wx.EVT_BUTTON, self.pushUp, self.upperButton)
        self.Bind(wx.EVT_BUTTON, self.pushDown, self.downButton)
        self.Bind(wx.EVT_BUTTON, self.pushRight, self.rightButton)
        self.Bind(wx.EVT_BUTTON, self.pushMpint, self.pintMinusButton)
        self.Bind(wx.EVT_BUTTON, self.pushZoomIn, self.button_4)
        self.Bind(wx.EVT_BUTTON, self.pushZoomOut, self.button_4_copy)
        self.Bind(wx.EVT_BUTTON, self.pushZoomOut, self.button_4_copy_copy)
        self.Bind(wx.EVT_BUTTON, self.pushCW2, self.rotateCCW2)
        self.Bind(wx.EVT_BUTTON, self.pushCW1, self.leftButton_copy_copy)
        self.Bind(wx.EVT_BUTTON, self.pushCCW1, self.leftButton_copy_copy_1)
        self.Bind(wx.EVT_BUTTON, self.pushCCW2, self.leftButton_copy_copy_copy_1)
        self.Bind(wx.EVT_BUTTON, self.pushRevPlus, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.pushRevMinus, self.button_1_copy)
        self.Bind(wx.EVT_BUTTON, self.pressUpdate, self.button_2)
        self.Bind(wx.EVT_BUTTON, self.pushLightOn, self.onLight)
        self.Bind(wx.EVT_BUTTON, self.pushColliOn, self.onLight_copy)
        self.Bind(wx.EVT_BUTTON, self.pushBSOn, self.onLight_copy_1)
        self.Bind(wx.EVT_BUTTON, self.pushLightOff, self.offLight)
        self.Bind(wx.EVT_BUTTON, self.pushColliOff, self.offLight_copy)
        self.Bind(wx.EVT_BUTTON, self.pushBSOff, self.offLight_copy_1)
        self.Bind(wx.EVT_BUTTON, self.pushAllEvac, self.button_3)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Centeringer.__set_properties
        self.SetTitle("frame_1")
        self.leftButton.SetMinSize((100, 32))
        self.pintPlusButton.SetMinSize((100, 32))
        self.upperButton.SetMinSize((100, 32))
        self.centerCombo.SetMinSize((80, 32))
        self.centerCombo.SetSelection(0)
        self.label_1.SetMinSize((25, 32))
        self.downButton.SetMinSize((100, 32))
        self.pintCombo.SetMinSize((80, 32))
        self.pintCombo.SetSelection(0)
        self.label_1_copy.SetMinSize((25, 32))
        self.rightButton.SetMinSize((100, 32))
        self.pintMinusButton.SetMinSize((100, 32))
        self.label_7.SetMinSize((41, 22))
        self.label_7.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.phiCombo.SetMinSize((87, 27))
        self.phiCombo.SetSelection(2)
        self.label_1_copy_1.SetMinSize((25, 32))
        self.label111.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.label_2.SetMinSize((100, 22))
        self.label_2.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.dispGonioX.SetMinSize((80, 32))
        self.label_2_copy.SetMinSize((100, 22))
        self.label_2_copy.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.dispGonioY.SetMinSize((80, 32))
        self.label_6.SetMinSize((120, 18))
        self.label_6_copy.SetMinSize((120, 18))
        self.label_6_copy_1.SetMinSize((120, 18))
        self.label_2_copy_1.SetMinSize((100, 22))
        self.label_2_copy_1.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.dispGonioZ.SetMinSize((80, 32))
        self.label_2_copy_2.SetMinSize((100, 22))
        self.label_2_copy_2.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.dispGonioZZ.SetMinSize((80, 32))
        self.button_3.SetMinSize((117, 32))
        self.button_3.SetFont(wx.Font(10, wx.DEFAULT, wx.SLANT, wx.BOLD, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Centeringer.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_3_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        sizer_10_copy_copy_copy_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10_copy_copy_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10_copy_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5_copy_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_2_copy_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2_copy_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5_copy_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5_copy_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5_copy_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_5_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_5.Add((20, 32), 0, wx.ADJUST_MINSIZE, 0)
        sizer_5.Add((20, 32), 0, 0, 0)
        sizer_5.Add(self.leftButton, 0, 0, 0)
        sizer_5.Add((20, 32), 0, 0, 0)
        sizer_5.Add((20, 32), 0, 0, 0)
        sizer_5.Add(self.pintPlusButton, 0, 0, 0)
        sizer_4.Add(sizer_5, 1, wx.EXPAND, 0)
        sizer_5_copy.Add((20, 32), 0, wx.ADJUST_MINSIZE, 0)
        sizer_5_copy.Add(self.upperButton, 0, 0, 0)
        sizer_6.Add(self.centerCombo, 0, 0, 0)
        sizer_6.Add(self.label_1, 0, wx.BOTTOM, 0)
        sizer_5_copy.Add(sizer_6, 1, wx.EXPAND, 0)
        sizer_5_copy.Add(self.downButton, 0, 0, 0)
        sizer_5_copy.Add((20, 32), 0, 0, 0)
        sizer_7.Add(self.pintCombo, 0, 0, 0)
        sizer_7.Add(self.label_1_copy, 0, wx.BOTTOM, 0)
        sizer_5_copy.Add(sizer_7, 1, wx.EXPAND, 0)
        sizer_4.Add(sizer_5_copy, 1, wx.EXPAND, 0)
        sizer_5_copy_1.Add((20, 32), 0, wx.ADJUST_MINSIZE, 0)
        sizer_5_copy_1.Add((20, 32), 0, 0, 0)
        sizer_5_copy_1.Add(self.rightButton, 0, 0, 0)
        sizer_5_copy_1.Add((20, 32), 0, 0, 0)
        sizer_5_copy_1.Add((20, 32), 0, 0, 0)
        sizer_5_copy_1.Add(self.pintMinusButton, 0, 0, 0)
        sizer_4.Add(sizer_5_copy_1, 1, wx.EXPAND, 0)
        sizer_5_copy_2.Add(sizer_11, 1, wx.EXPAND, 0)
        sizer_5_copy_2.Add(self.label_7, 0, wx.ADJUST_MINSIZE, 0)
        sizer_5_copy_2.Add(self.button_4, 0, wx.ADJUST_MINSIZE, 0)
        sizer_5_copy_2.Add(self.button_4_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_5_copy_2.Add(self.button_4_copy_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_12.Add(self.label_4_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_12.Add(self.dispPhi_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_12.Add(self.label_8, 0, wx.ADJUST_MINSIZE, 0)
        sizer_5_copy_2.Add(sizer_12, 1, wx.EXPAND, 0)
        sizer_4.Add(sizer_5_copy_2, 1, wx.EXPAND, 0)
        sizer_5_copy_3.Add(self.rotateCCW2, 0, 0, 0)
        sizer_5_copy_3.Add(self.leftButton_copy_copy, 0, 0, 0)
        sizer_8.Add(self.phiCombo, 0, 0, 0)
        sizer_8.Add(self.label_1_copy_1, 0, wx.BOTTOM, 0)
        sizer_5_copy_3.Add(sizer_8, 1, wx.EXPAND, 0)
        sizer_5_copy_3.Add(self.leftButton_copy_copy_1, 0, 0, 0)
        sizer_5_copy_3.Add(self.leftButton_copy_copy_copy_1, 0, 0, 0)
        sizer_10.Add(self.label_4, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10.Add(self.dispPhi, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10.Add(self.label_5, 0, wx.ADJUST_MINSIZE, 0)
        sizer_5_copy_3.Add(sizer_10, 1, wx.EXPAND, 0)
        sizer_4.Add(sizer_5_copy_3, 1, wx.EXPAND, 0)
        sizer_2.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_2.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_5_copy_4.Add(sizer_2, 1, wx.EXPAND, 0)
        sizer_2_copy.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_2_copy.Add(self.button_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_5_copy_4.Add(sizer_2_copy, 1, wx.EXPAND, 0)
        sizer_2_copy_1.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_2_copy_1.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_5_copy_4.Add(sizer_2_copy_1, 1, wx.EXPAND, 0)
        sizer_2_copy_2.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_2_copy_2.Add(self.button_1_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_5_copy_4.Add(sizer_2_copy_2, 1, wx.EXPAND, 0)
        sizer_2_copy_3.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_2_copy_3.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_5_copy_4.Add(sizer_2_copy_3, 1, wx.EXPAND, 0)
        sizer_4.Add(sizer_5_copy_4, 1, wx.EXPAND, 0)
        self.notebook_1_pane_1.SetSizer(sizer_4)
        self.notebook_1.AddPage(self.notebook_1_pane_1, "Centering")
        sizer_3.Add(self.notebook_1, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_9.Add(self.label111, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy.Add(self.label_2, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy.Add(self.dispGonioX, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy.Add(self.label_3, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy.Add(self.button_2, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_9.Add(sizer_10_copy_copy, 1, wx.EXPAND, 0)
        sizer_10_copy_copy_copy.Add(self.label_2_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy_copy.Add(self.dispGonioY, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy_copy.Add(self.label_3_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy_copy.Add((200, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy_copy.Add(self.label_6, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy_copy.Add((100, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy_copy.Add(self.label_6_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy_copy.Add((100, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy_copy.Add(self.label_6_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_9.Add(sizer_10_copy_copy_copy, 1, wx.EXPAND, 0)
        sizer_10_copy_copy_copy_1.Add(self.label_2_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy_copy_1.Add(self.dispGonioZ, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy_copy_1.Add(self.label_3_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy_copy_1.Add((200, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy_copy_1.Add(self.onLight, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy_copy_1.Add((100, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy_copy_1.Add(self.onLight_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy_copy_1.Add((100, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy_copy_1.Add(self.onLight_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy_copy_1.Add((200, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_9.Add(sizer_10_copy_copy_copy_1, 1, wx.EXPAND, 0)
        sizer_10_copy_copy_copy_2.Add(self.label_2_copy_2, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy_copy_2.Add(self.dispGonioZZ, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy_copy_2.Add(self.label_3_copy_2, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy_copy_2.Add((200, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy_copy_2.Add(self.offLight, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy_copy_2.Add((100, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy_copy_2.Add(self.offLight_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy_copy_2.Add((100, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy_copy_2.Add(self.offLight_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy_copy_2.Add((100, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy_copy_2.Add(self.button_3, 0, wx.ADJUST_MINSIZE, 0)
        sizer_9.Add(sizer_10_copy_copy_copy_2, 1, wx.EXPAND, 0)
        sizer_3_copy.Add(sizer_9, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_3_copy, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def pushLeft(self, event): # wxGlade: Centeringer.<event_handler>
        print "Event handler `pushLeft' not implemented!"
        event.Skip()

    def pushPpint(self, event): # wxGlade: Centeringer.<event_handler>
        print "Event handler `pushPpint' not implemented!"
        event.Skip()

    def pushUp(self, event): # wxGlade: Centeringer.<event_handler>
        print "Event handler `pushUp' not implemented!"
        event.Skip()

    def pushDown(self, event): # wxGlade: Centeringer.<event_handler>
        print "Event handler `pushDown' not implemented!"
        event.Skip()

    def pushRight(self, event): # wxGlade: Centeringer.<event_handler>
        print "Event handler `pushRight' not implemented!"
        event.Skip()

    def pushMpint(self, event): # wxGlade: Centeringer.<event_handler>
        print "Event handler `pushMpint' not implemented!"
        event.Skip()

    def pushZoomIn(self, event): # wxGlade: Centeringer.<event_handler>
        print "Event handler `pushZoomIn' not implemented!"
        event.Skip()

    def pushZoomOut(self, event): # wxGlade: Centeringer.<event_handler>
        print "Event handler `pushZoomOut' not implemented!"
        event.Skip()

    def pushCW2(self, event): # wxGlade: Centeringer.<event_handler>
        print "Event handler `pushCW2' not implemented!"
        event.Skip()

    def pushCW1(self, event): # wxGlade: Centeringer.<event_handler>
        print "Event handler `pushCW1' not implemented!"
        event.Skip()

    def pushCCW1(self, event): # wxGlade: Centeringer.<event_handler>
        print "Event handler `pushCCW1' not implemented!"
        event.Skip()

    def pushCCW2(self, event): # wxGlade: Centeringer.<event_handler>
        print "Event handler `pushCCW2' not implemented!"
        event.Skip()

    def pushRevPlus(self, event): # wxGlade: Centeringer.<event_handler>
        print "Event handler `pushRevPlus' not implemented!"
        event.Skip()

    def pushRevMinus(self, event): # wxGlade: Centeringer.<event_handler>
        print "Event handler `pushRevMinus' not implemented!"
        event.Skip()

    def pressUpdate(self, event): # wxGlade: Centeringer.<event_handler>
        print "Event handler `pressUpdate' not implemented!"
        event.Skip()

    def pushLightOn(self, event): # wxGlade: Centeringer.<event_handler>
        print "Event handler `pushLightOn' not implemented!"
        event.Skip()

    def pushColliOn(self, event): # wxGlade: Centeringer.<event_handler>
        print "Event handler `pushColliOn' not implemented!"
        event.Skip()

    def pushBSOn(self, event): # wxGlade: Centeringer.<event_handler>
        print "Event handler `pushBSOn' not implemented!"
        event.Skip()

    def pushLightOff(self, event): # wxGlade: Centeringer.<event_handler>
        print "Event handler `pushLightOff' not implemented!"
        event.Skip()

    def pushColliOff(self, event): # wxGlade: Centeringer.<event_handler>
        print "Event handler `pushColliOff' not implemented!"
        event.Skip()

    def pushBSOff(self, event): # wxGlade: Centeringer.<event_handler>
        print "Event handler `pushBSOff' not implemented!"
        event.Skip()

    def pushAllEvac(self, event): # wxGlade: Centeringer.<event_handler>
        print "Event handler `pushAllEvac' not implemented!"
        event.Skip()

# end of class Centeringer


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    Centering_tool_for_BL32XU = Centeringer(None, -1, "")
    app.SetTopWindow(Centering_tool_for_BL32XU)
    Centering_tool_for_BL32XU.Show()

    app.MainLoop()
