#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Wed May 26 12:10:55 2010


import wx
import time
import socket
import sys
sys.path.append("/isilon/BL32XU/BLsoft/PPPP/")
import datetime
from Cryo import *

# begin wxGlade: extracode
# end wxGlade

class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.label_1 = wx.StaticText(self, -1, "Cryo Z")
        self.button_1 = wx.Button(self, -1, "On")
        self.button_2 = wx.Button(self, -1, "Off")


        self.__set_properties()
        self.__do_layout()

        host = '172.24.242.41'
        port = 10101
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.connect((host,port))
	self.cryoz=Cryo(s)

        self.Bind(wx.EVT_BUTTON, self.pushOn, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.pushOff, self.button_2)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("Cryo Z controller")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(self.label_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_2.Add(self.button_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_2.Add(self.button_2, 0, wx.ADJUST_MINSIZE, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def pushOn(self, event): # wxGlade: MyFrame.<event_handler>
	print "ON"
	self.cryoz.on()

    def pushOff(self, event): # wxGlade: MyFrame.<event_handler>
	print "OFF"
	self.cryoz.off()

# end of class MyFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
