#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Thu May  6 02:01:56 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.notebook_1 = wx.Notebook(self, -1, style=0)
        self.TCStab = wx.Panel(self.notebook_1, -1)
        self.FEStab = wx.Panel(self.notebook_1, -1)
        self.label_6 = wx.StaticText(self.FEStab, -1, "Current status")
        self.label_7 = wx.StaticText(self.FEStab, -1, "Height[mm]", style=wx.ALIGN_CENTRE)
        self.label_8 = wx.StaticText(self.FEStab, -1, "Width[mm]", style=wx.ALIGN_CENTRE)
        self.label_9 = wx.StaticText(self.FEStab, -1, "Vertical[mm]", style=wx.ALIGN_CENTRE)
        self.label_10 = wx.StaticText(self.FEStab, -1, "Horizontal[mm]", style=wx.ALIGN_CENTRE)
        self.text_ctrl_1 = wx.TextCtrl(self.FEStab, -1, "", style=wx.TE_READONLY)
        self.text_ctrl_1_copy = wx.TextCtrl(self.FEStab, -1, "", style=wx.TE_READONLY)
        self.text_ctrl_1_copy_1 = wx.TextCtrl(self.FEStab, -1, "", style=wx.TE_READONLY)
        self.text_ctrl_1_copy_2 = wx.TextCtrl(self.FEStab, -1, "", style=wx.TE_READONLY)
        self.label_6_copy = wx.StaticText(self.TCStab, -1, "Current status")
        self.label_7_copy = wx.StaticText(self.TCStab, -1, "Height[mm]", style=wx.ALIGN_CENTRE)
        self.label_8_copy = wx.StaticText(self.TCStab, -1, "Width[mm]", style=wx.ALIGN_CENTRE)
        self.label_9_copy = wx.StaticText(self.TCStab, -1, "Vertical[mm]", style=wx.ALIGN_CENTRE)
        self.label_10_copy = wx.StaticText(self.TCStab, -1, "Horizontal[mm]", style=wx.ALIGN_CENTRE)
        self.text_ctrl_1_copy_3 = wx.TextCtrl(self.TCStab, -1, "", style=wx.TE_READONLY)
        self.text_ctrl_1_copy_copy = wx.TextCtrl(self.TCStab, -1, "", style=wx.TE_READONLY)
        self.text_ctrl_1_copy_1_copy = wx.TextCtrl(self.TCStab, -1, "", style=wx.TE_READONLY)
        self.text_ctrl_1_copy_2_copy = wx.TextCtrl(self.TCStab, -1, "", style=wx.TE_READONLY)
        self.button_1 = wx.Button(self, -1, "Pop up")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.pressButton, self.button_1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("frame_2")
        self.label_6.SetMinSize((84, 20))
        self.label_7.SetMinSize((90, 20))
        self.label_8.SetMinSize((90, 20))
        self.label_9.SetMinSize((90, 20))
        self.label_10.SetMinSize((90, 20))
        self.text_ctrl_1.SetMinSize((80, 20))
        self.text_ctrl_1.SetBackgroundColour(wx.Colour(255, 255, 0))
        self.text_ctrl_1_copy.SetMinSize((80, 20))
        self.text_ctrl_1_copy.SetBackgroundColour(wx.Colour(255, 255, 0))
        self.text_ctrl_1_copy_1.SetMinSize((80, 20))
        self.text_ctrl_1_copy_1.SetBackgroundColour(wx.Colour(255, 255, 0))
        self.text_ctrl_1_copy_2.SetMinSize((80, 20))
        self.text_ctrl_1_copy_2.SetBackgroundColour(wx.Colour(255, 255, 0))
        self.label_6_copy.SetMinSize((84, 20))
        self.label_7_copy.SetMinSize((90, 20))
        self.label_8_copy.SetMinSize((90, 20))
        self.label_9_copy.SetMinSize((90, 20))
        self.label_10_copy.SetMinSize((90, 20))
        self.text_ctrl_1_copy_3.SetMinSize((80, 20))
        self.text_ctrl_1_copy_3.SetBackgroundColour(wx.Colour(255, 255, 0))
        self.text_ctrl_1_copy_copy.SetMinSize((80, 20))
        self.text_ctrl_1_copy_copy.SetBackgroundColour(wx.Colour(255, 255, 0))
        self.text_ctrl_1_copy_1_copy.SetMinSize((80, 20))
        self.text_ctrl_1_copy_1_copy.SetBackgroundColour(wx.Colour(255, 255, 0))
        self.text_ctrl_1_copy_2_copy.SetMinSize((80, 20))
        self.text_ctrl_1_copy_2_copy.SetBackgroundColour(wx.Colour(255, 255, 0))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10_copy_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_10_copy_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_10 = wx.BoxSizer(wx.VERTICAL)
        sizer_10.Add(self.label_6, 0, 0, 0)
        sizer_10.Add(self.label_7, 0, 0, 0)
        sizer_10.Add(self.label_8, 0, 0, 0)
        sizer_10.Add(self.label_9, 0, 0, 0)
        sizer_10.Add(self.label_10, 0, 0, 0)
        sizer_9.Add(sizer_10, 1, wx.EXPAND, 0)
        sizer_10_copy.Add((20, 20), 0, 0, 0)
        sizer_10_copy.Add(self.text_ctrl_1, 0, 0, 0)
        sizer_10_copy.Add(self.text_ctrl_1_copy, 0, 0, 0)
        sizer_10_copy.Add(self.text_ctrl_1_copy_1, 0, 0, 0)
        sizer_10_copy.Add(self.text_ctrl_1_copy_2, 0, 0, 0)
        sizer_9.Add(sizer_10_copy, 1, wx.EXPAND, 0)
        self.FEStab.SetSizer(sizer_9)
        sizer_10_copy_1.Add(self.label_6_copy, 0, 0, 0)
        sizer_10_copy_1.Add(self.label_7_copy, 0, 0, 0)
        sizer_10_copy_1.Add(self.label_8_copy, 0, 0, 0)
        sizer_10_copy_1.Add(self.label_9_copy, 0, 0, 0)
        sizer_10_copy_1.Add(self.label_10_copy, 0, 0, 0)
        sizer_9_copy.Add(sizer_10_copy_1, 1, wx.EXPAND, 0)
        sizer_10_copy_copy.Add((20, 20), 0, 0, 0)
        sizer_10_copy_copy.Add(self.text_ctrl_1_copy_3, 0, 0, 0)
        sizer_10_copy_copy.Add(self.text_ctrl_1_copy_copy, 0, 0, 0)
        sizer_10_copy_copy.Add(self.text_ctrl_1_copy_1_copy, 0, 0, 0)
        sizer_10_copy_copy.Add(self.text_ctrl_1_copy_2_copy, 0, 0, 0)
        sizer_9_copy.Add(sizer_10_copy_copy, 1, wx.EXPAND, 0)
        self.TCStab.SetSizer(sizer_9_copy)
        sizer_2.Add(self.notebook_1, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        sizer_1.Add(self.button_1, 0, 0, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def pressButton(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `pressButton' not implemented!"
        event.Skip()

# end of class MainFrame


class MyPanel1(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyPanel1.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.button_2 = wx.Button(self, -1, "button_2")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyPanel1.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyPanel1.__do_layout
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(self.button_2, 0, 0, 0)
        self.SetSizer(sizer_3)
        sizer_3.Fit(self)
        # end wxGlade

# end of class MyPanel1


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MainFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
