#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Fri May  7 00:46:31 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class Centeringer(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Centeringer.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.notebook_1 = wx.Notebook(self, -1, style=0)
        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, -1)
        self.leftButton = wx.Button(self.notebook_1_pane_1, -1, "Left")
        self.pintPlusButton = wx.Button(self.notebook_1_pane_1, -1, "+ pint")
        self.upperButton = wx.Button(self.notebook_1_pane_1, -1, "Up")
        self.centerCombo = wx.ComboBox(self.notebook_1_pane_1, -1, choices=["1000", "500", "200", "100", "50", "20", "10", "5", "1", "0.5"], style=wx.CB_DROPDOWN)
        self.label_1 = wx.StaticText(self.notebook_1_pane_1, -1, "[um]", style=wx.ALIGN_CENTRE)
        self.downButton = wx.Button(self.notebook_1_pane_1, -1, "Down")
        self.pintCombo = wx.ComboBox(self.notebook_1_pane_1, -1, choices=["1000", "500", "200", "100", "50", "20", "10", "5", "1", "0.5"], style=wx.CB_DROPDOWN)
        self.label_1_copy = wx.StaticText(self.notebook_1_pane_1, -1, "[um]", style=wx.ALIGN_CENTRE)
        self.rightButton = wx.Button(self.notebook_1_pane_1, -1, "Right")
        self.pintMinusButton = wx.Button(self.notebook_1_pane_1, -1, "- pint")
        self.rotateCCW2 = wx.Button(self.notebook_1_pane_1, -1, "++")
        self.leftButton_copy_copy = wx.Button(self.notebook_1_pane_1, -1, "+")
        self.combo_box_2 = wx.ComboBox(self.notebook_1_pane_1, -1, choices=["30", "45", "90", "180"], style=wx.CB_DROPDOWN)
        self.label_1_copy_1 = wx.StaticText(self.notebook_1_pane_1, -1, "[deg.]", style=wx.ALIGN_CENTRE)
        self.leftButton_copy_copy_1 = wx.Button(self.notebook_1_pane_1, -1, "-")
        self.leftButton_copy_copy_copy_1 = wx.Button(self.notebook_1_pane_1, -1, "--")
        self.label_4 = wx.StaticText(self.notebook_1_pane_1, -1, "current PHI")
        self.text_ctrl_2 = wx.TextCtrl(self.notebook_1_pane_1, -1, "", style=wx.TE_READONLY)
        self.label_5 = wx.StaticText(self.notebook_1_pane_1, -1, "[deg.]")
        self.button_1 = wx.Button(self.notebook_1_pane_1, -1, "Reverse(+)")
        self.button_1_copy = wx.Button(self.notebook_1_pane_1, -1, "Reverse(-)")
        self.notebook_1_pane_2 = wx.Panel(self.notebook_1, -1)
        self.label111 = wx.StaticText(self, -1, "Current status")
        self.label_2 = wx.StaticText(self, -1, "gonio x")
        self.text_ctrl_1 = wx.TextCtrl(self, -1, "")
        self.label_3 = wx.StaticText(self, -1, "[mm]")
        self.button_2 = wx.Button(self, -1, "Update")
        self.label_2_copy = wx.StaticText(self, -1, "gonio y")
        self.text_ctrl_1_copy = wx.TextCtrl(self, -1, "")
        self.label_3_copy = wx.StaticText(self, -1, "[mm]")
        self.label_2_copy_1 = wx.StaticText(self, -1, "gonio z")
        self.text_ctrl_1_copy_1 = wx.TextCtrl(self, -1, "")
        self.label_3_copy_1 = wx.StaticText(self, -1, "[mm]")
        self.label_2_copy_2 = wx.StaticText(self, -1, "gonio zz")
        self.text_ctrl_1_copy_2 = wx.TextCtrl(self, -1, "")
        self.label_3_copy_2 = wx.StaticText(self, -1, "[mm]")

        #self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.pushLeft, self.leftButton)
        self.Bind(wx.EVT_BUTTON, self.pushPpint, self.pintPlusButton)
        self.Bind(wx.EVT_BUTTON, self.pushUp, self.upperButton)
        self.Bind(wx.EVT_BUTTON, self.pushDown, self.downButton)
        self.Bind(wx.EVT_BUTTON, self.pushRight, self.rightButton)
        self.Bind(wx.EVT_BUTTON, self.pushMpint, self.pintMinusButton)
        self.Bind(wx.EVT_BUTTON, self.pushCW2, self.rotateCCW2)
        self.Bind(wx.EVT_BUTTON, self.pushCW1, self.leftButton_copy_copy)
        self.Bind(wx.EVT_BUTTON, self.pushCCW1, self.leftButton_copy_copy_1)
        self.Bind(wx.EVT_BUTTON, self.pushCCW2, self.leftButton_copy_copy_copy_1)
        self.Bind(wx.EVT_BUTTON, self.pushRevPlus, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.pushRevMinus, self.button_1_copy)
        self.Bind(wx.EVT_BUTTON, self.pressUpdate, self.button_2)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Centeringer.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_3_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        sizer_10_copy_copy_copy_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10_copy_copy_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10_copy_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5_copy_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_2_copy_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2_copy_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5_copy_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5_copy_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_5_copy_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_5_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_5.Add((20, 32), 0, wx.ADJUST_MINSIZE, 0)
        sizer_5.Add((20, 32), 0, 0, 0)
        sizer_5.Add(self.leftButton, 0, 0, 0)
        sizer_5.Add((20, 32), 0, 0, 0)
        sizer_5.Add((20, 32), 0, 0, 0)
        sizer_5.Add(self.pintPlusButton, 0, 0, 0)
        sizer_4.Add(sizer_5, 1, wx.EXPAND, 0)
        sizer_5_copy.Add((20, 32), 0, wx.ADJUST_MINSIZE, 0)
        sizer_5_copy.Add(self.upperButton, 0, 0, 0)
        sizer_6.Add(self.centerCombo, 0, 0, 0)
        sizer_6.Add(self.label_1, 0, wx.BOTTOM, 0)
        sizer_5_copy.Add(sizer_6, 1, wx.EXPAND, 0)
        sizer_5_copy.Add(self.downButton, 0, 0, 0)
        sizer_5_copy.Add((20, 32), 0, 0, 0)
        sizer_7.Add(self.pintCombo, 0, 0, 0)
        sizer_7.Add(self.label_1_copy, 0, wx.BOTTOM, 0)
        sizer_5_copy.Add(sizer_7, 1, wx.EXPAND, 0)
        sizer_4.Add(sizer_5_copy, 1, wx.EXPAND, 0)
        sizer_5_copy_1.Add((20, 32), 0, wx.ADJUST_MINSIZE, 0)
        sizer_5_copy_1.Add((20, 32), 0, 0, 0)
        sizer_5_copy_1.Add(self.rightButton, 0, 0, 0)
        sizer_5_copy_1.Add((20, 32), 0, 0, 0)
        sizer_5_copy_1.Add((20, 32), 0, 0, 0)
        sizer_5_copy_1.Add(self.pintMinusButton, 0, 0, 0)
        sizer_4.Add(sizer_5_copy_1, 1, wx.EXPAND, 0)
        sizer_4.Add(sizer_5_copy_2, 1, wx.EXPAND, 0)
        sizer_5_copy_3.Add(self.rotateCCW2, 0, 0, 0)
        sizer_5_copy_3.Add(self.leftButton_copy_copy, 0, 0, 0)
        sizer_8.Add(self.combo_box_2, 0, 0, 0)
        sizer_8.Add(self.label_1_copy_1, 0, wx.BOTTOM, 0)
        sizer_5_copy_3.Add(sizer_8, 1, wx.EXPAND, 0)
        sizer_5_copy_3.Add(self.leftButton_copy_copy_1, 0, 0, 0)
        sizer_5_copy_3.Add(self.leftButton_copy_copy_copy_1, 0, 0, 0)
        sizer_10.Add(self.label_4, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10.Add(self.text_ctrl_2, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10.Add(self.label_5, 0, wx.ADJUST_MINSIZE, 0)
        sizer_5_copy_3.Add(sizer_10, 1, wx.EXPAND, 0)
        sizer_4.Add(sizer_5_copy_3, 1, wx.EXPAND, 0)
        sizer_2.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_2.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_5_copy_4.Add(sizer_2, 1, wx.EXPAND, 0)
        sizer_2_copy.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_2_copy.Add(self.button_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_5_copy_4.Add(sizer_2_copy, 1, wx.EXPAND, 0)
        sizer_2_copy_1.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_2_copy_1.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_5_copy_4.Add(sizer_2_copy_1, 1, wx.EXPAND, 0)
        sizer_2_copy_2.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_2_copy_2.Add(self.button_1_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_5_copy_4.Add(sizer_2_copy_2, 1, wx.EXPAND, 0)
        sizer_2_copy_3.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_2_copy_3.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_5_copy_4.Add(sizer_2_copy_3, 1, wx.EXPAND, 0)
        sizer_4.Add(sizer_5_copy_4, 1, wx.EXPAND, 0)
        self.notebook_1_pane_1.SetSizer(sizer_4)
        self.notebook_1.AddPage(self.notebook_1_pane_1, "Centering")
        self.notebook_1.AddPage(self.notebook_1_pane_2, "Devices")
        sizer_3.Add(self.notebook_1, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_9.Add(self.label111, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy.Add(self.label_2, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy.Add(self.text_ctrl_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy.Add(self.label_3, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy.Add(self.button_2, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_9.Add(sizer_10_copy_copy, 1, wx.EXPAND, 0)
        sizer_10_copy_copy_copy.Add(self.label_2_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy_copy.Add(self.text_ctrl_1_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy_copy.Add(self.label_3_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_9.Add(sizer_10_copy_copy_copy, 1, wx.EXPAND, 0)
        sizer_10_copy_copy_copy_1.Add(self.label_2_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy_copy_1.Add(self.text_ctrl_1_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy_copy_1.Add(self.label_3_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_9.Add(sizer_10_copy_copy_copy_1, 1, wx.EXPAND, 0)
        sizer_10_copy_copy_copy_2.Add(self.label_2_copy_2, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy_copy_2.Add(self.text_ctrl_1_copy_2, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10_copy_copy_copy_2.Add(self.label_3_copy_2, 0, wx.ADJUST_MINSIZE, 0)
        sizer_9.Add(sizer_10_copy_copy_copy_2, 1, wx.EXPAND, 0)
        sizer_3_copy.Add(sizer_9, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_3_copy, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def pushLeft(self, event): # wxGlade: Centeringer.<event_handler>
        print "Event handler `pushLeft' not implemented!"
        event.Skip()

    def pushPpint(self, event): # wxGlade: Centeringer.<event_handler>
        print "Event handler `pushPpint' not implemented!"
        event.Skip()

    def pushUp(self, event): # wxGlade: Centeringer.<event_handler>
        print "Event handler `pushUp' not implemented!"
        event.Skip()

    def pushDown(self, event): # wxGlade: Centeringer.<event_handler>
        print "Event handler `pushDown' not implemented!"
        event.Skip()

    def pushRight(self, event): # wxGlade: Centeringer.<event_handler>
        print "Event handler `pushRight' not implemented!"
        event.Skip()

    def pushMpint(self, event): # wxGlade: Centeringer.<event_handler>
        print "Event handler `pushMpint' not implemented!"
        event.Skip()

    def pushCW2(self, event): # wxGlade: Centeringer.<event_handler>
        print "Event handler `pushCW2' not implemented!"
        event.Skip()

    def pushCW1(self, event): # wxGlade: Centeringer.<event_handler>
        print "Event handler `pushCW1' not implemented!"
        event.Skip()

    def pushCCW1(self, event): # wxGlade: Centeringer.<event_handler>
        print "Event handler `pushCCW1' not implemented!"
        event.Skip()

    def pushCCW2(self, event): # wxGlade: Centeringer.<event_handler>
        print "Event handler `pushCCW2' not implemented!"
        event.Skip()

    def OnMouseWheel(self,event):
	s = event.GetPosition()
        print 'OnMouseLeave' + str(pos)


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = Centeringer(None, -1, "MouseEvent")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
