#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Thu Jul  1 21:30:15 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class MainWindow(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainWindow.__init__
        kwds["style"] = wx.ICONIZE|wx.CAPTION|wx.MINIMIZE|wx.CLOSE_BOX|wx.MINIMIZE_BOX|wx.MAXIMIZE_BOX|wx.SYSTEM_MENU|wx.RESIZE_BORDER|wx.CLIP_CHILDREN
        wx.Frame.__init__(self, *args, **kwds)
        self.notebook_1 = wx.Notebook(self, -1, style=0)
        self.notebook_1_pane_2 = wx.Panel(self.notebook_1, -1)
        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, -1)
        self.notebook_2 = wx.Notebook(self.notebook_1_pane_1, -1, style=0)
        self.notebook_2_pane_3 = wx.Panel(self.notebook_2, -1)
        self.notebook_2_pane_2 = wx.Panel(self.notebook_2, -1)
        self.notebook_2_pane_1 = wx.Panel(self.notebook_2, -1)
        self.notebook_LogMessage = wx.Notebook(self.notebook_1_pane_1, -1, style=0)
        self.notebook_2_pane_2_copy = wx.Panel(self.notebook_LogMessage, -1, style=wx.RAISED_BORDER|wx.TAB_TRAVERSAL)
        self.notebook_2_pane_1_copy = wx.Panel(self.notebook_LogMessage, -1, style=wx.RAISED_BORDER|wx.TAB_TRAVERSAL)
        self.sizer_17_copy_copy_staticbox = wx.StaticBox(self.notebook_1_pane_1, -1, "Job List")
        self.sizer_55_copy_staticbox = wx.StaticBox(self.notebook_1_pane_1, -1, "Massage")
        self.sizer_47_staticbox = wx.StaticBox(self.notebook_1_pane_1, -1, "Information")
        self.sizer_48_copy_copy_staticbox = wx.StaticBox(self.notebook_2_pane_1, -1, "Parameters")
        self.sizer_11_copy_1_copy_staticbox = wx.StaticBox(self.notebook_2_pane_2, -1, "cell parameters")
        self.sizer_44_staticbox = wx.StaticBox(self.notebook_2_pane_3, -1, "Scaling parameters")
        self.sizer_Action_staticbox = wx.StaticBox(self.notebook_1_pane_1, -1, "Action")
        self.sizer_17_copy_copy_copy_staticbox = wx.StaticBox(self.notebook_1_pane_2, -1, "jobs on Umic")
        self.sizer_8_staticbox = wx.StaticBox(self.notebook_1_pane_2, -1, "Compress")
        self.sizer_8_copy_staticbox = wx.StaticBox(self.notebook_1_pane_2, -1, "Clean up")
        self.sizer_9_staticbox = wx.StaticBox(self.notebook_1_pane_2, -1, "Message")
        self.sizer_34_copy_copy_copy_staticbox = wx.StaticBox(self.notebook_1_pane_1, -1, "Setup")
        
        # Menu Bar
        self.frame_1_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.NewId(), "open job list", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.NewId(), "save job list", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.NewId(), "exit", "", wx.ITEM_NORMAL)
        self.frame_1_menubar.Append(wxglade_tmp_menu, "File")
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.NewId(), "Send Message", "", wx.ITEM_NORMAL)
        self.frame_1_menubar.Append(wxglade_tmp_menu, "Tools")
        self.SetMenuBar(self.frame_1_menubar)
        # Menu Bar end
        self.frame_1_statusbar = self.CreateStatusBar(1, 0)
        
        # Tool Bar
        self.frame_1_toolbar = wx.ToolBar(self, -1)
        self.SetToolBar(self.frame_1_toolbar)
        # Tool Bar end
        self.label_prefix = wx.StaticText(self.notebook_1_pane_1, -1, "Prefix Directory")
        self.text_ctrl_1 = wx.TextCtrl(self.notebook_1_pane_1, -1, " ----------", style=wx.TE_CENTRE)
        self.button_show_dir_list_1 = wx.Button(self.notebook_1_pane_1, -1, "...")
        self.static_line_3_copy_copy_copy_copy = wx.StaticLine(self.notebook_1_pane_1, -1, style=wx.LI_VERTICAL)
        self.list_ctrl_job_list = wx.ListCtrl(self.notebook_1_pane_1, -1, style=wx.LC_REPORT|wx.LC_SINGLE_SEL|wx.LC_VRULES|wx.SUNKEN_BORDER)
        self.button_ListCtrl_Append = wx.Button(self.notebook_1_pane_1, -1, "Append")
        self.button_ListCtrl_Delete = wx.Button(self.notebook_1_pane_1, -1, "Delete")
        self.button_ListCtrl_clear_all = wx.Button(self.notebook_1_pane_1, -1, "Clear All")
        self.button_ViewInputFile = wx.Button(self.notebook_1_pane_1, -1, "View Input")
        self.button_ViewLog = wx.Button(self.notebook_1_pane_1, -1, "View Log")
        self.button_ListCtrl_Update = wx.Button(self.notebook_1_pane_1, -1, "Update")
        self.text_ctrl_LogMsg = wx.TextCtrl(self.notebook_2_pane_1_copy, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY)
        self.text_ctrl_ErrorMsg = wx.TextCtrl(self.notebook_2_pane_2_copy, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY)
        self.label_server_name_1 = wx.StaticText(self.notebook_1_pane_1, -1, "server name :")
        self.label_server_name_2 = wx.StaticText(self.notebook_1_pane_1, -1, "?????.??????.??.??")
        self.static_line_7 = wx.StaticLine(self.notebook_1_pane_1, -1, style=wx.LI_VERTICAL)
        self.label_user_name_1 = wx.StaticText(self.notebook_1_pane_1, -1, "user name :")
        self.label_user_name_2 = wx.StaticText(self.notebook_1_pane_1, -1, "?????")
        self.label_5_copy_2_copy = wx.StaticText(self.notebook_2_pane_1, -1, "Detector")
        self.text_ctrl_detector = wx.TextCtrl(self.notebook_2_pane_1, -1, "")
        self.label_6_copy_2_copy = wx.StaticText(self.notebook_2_pane_1, -1, "distance")
        self.text_ctrl_distance = wx.TextCtrl(self.notebook_2_pane_1, -1, "")
        self.label_5_copy_copy_copy = wx.StaticText(self.notebook_2_pane_1, -1, "osc. start")
        self.text_ctrl_osc_start = wx.TextCtrl(self.notebook_2_pane_1, -1, "")
        self.label_6_copy_copy_copy = wx.StaticText(self.notebook_2_pane_1, -1, "step")
        self.text_ctrl_step = wx.TextCtrl(self.notebook_2_pane_1, -1, "")
        self.label_5_copy_1_copy_1_copy = wx.StaticText(self.notebook_2_pane_1, -1, "beam X")
        self.text_ctrl_beamx = wx.TextCtrl(self.notebook_2_pane_1, -1, "")
        self.label_6_copy_1_copy_copy = wx.StaticText(self.notebook_2_pane_1, -1, "beam Y")
        self.text_ctrl_beamy = wx.TextCtrl(self.notebook_2_pane_1, -1, "")
        self.label_5_copy_1_copy_copy_copy = wx.StaticText(self.notebook_2_pane_1, -1, "wavelength")
        self.text_ctrl_wavelength = wx.TextCtrl(self.notebook_2_pane_1, -1, "")
        self.label_7_copy_1_copy_copy = wx.StaticText(self.notebook_2_pane_1, -1, "Job Control")
        self.choice_1_XDS_job_control = wx.Choice(self.notebook_2_pane_1, -1, choices=["All", "CORRECT", "COLSPOT IDXREF", "IDXREF DEFPIX", "DEFPIX INTEGRATE CORRECT", "XYCORR INIT COLSPOT IDXREF DEFPIX XPLAN"])
        self.label_7_copy_2_copy = wx.StaticText(self.notebook_2_pane_1, -1, "Integration range")
        self.label_8_copy_1_copy = wx.StaticText(self.notebook_2_pane_1, -1, "from")
        self.text_ctrl_integrate_start = wx.TextCtrl(self.notebook_2_pane_1, -1, "")
        self.label_9_copy_1_copy = wx.StaticText(self.notebook_2_pane_1, -1, "to")
        self.text_ctrl_integrate_end = wx.TextCtrl(self.notebook_2_pane_1, -1, "")
        self.label_7_copy_copy_copy_copy_copy = wx.StaticText(self.notebook_2_pane_1, -1, "Resolution range")
        self.label_8_copy_copy_copy_copy_copy = wx.StaticText(self.notebook_2_pane_1, -1, "low")
        self.text_ctrl_low_resolution = wx.TextCtrl(self.notebook_2_pane_1, -1, "")
        self.label_9_copy_copy_copy_copy_copy = wx.StaticText(self.notebook_2_pane_1, -1, "high")
        self.text_ctrl_high_resolution = wx.TextCtrl(self.notebook_2_pane_1, -1, "")
        self.label_10_copy_copy = wx.StaticText(self.notebook_2_pane_1, -1, "BeamLine")
        self.choice_BL = wx.Choice(self.notebook_2_pane_1, -1, choices=["BL26B1", "BL26B2", "BL32XU", "BL38B1", "BL41XU"])
        self.label_filename_temp_copy = wx.StaticText(self.notebook_2_pane_1, -1, "FIle name template")
        self.text_ctrl_XDS_filename_template = wx.TextCtrl(self.notebook_2_pane_1, -1, "")
        self.label_data_directory_copy_copy = wx.StaticText(self.notebook_2_pane_1, -1, "Data Directory")
        self.text_ctrl_image_data_dir = wx.TextCtrl(self.notebook_2_pane_1, -1, "")
        self.button_show_dir_list_2 = wx.Button(self.notebook_2_pane_1, -1, "...")
        self.label_data_directory_copy_copy_copy = wx.StaticText(self.notebook_2_pane_1, -1, "Output Directory")
        self.text_ctrl_output_data_dir = wx.TextCtrl(self.notebook_2_pane_1, -1, "")
        self.button_show_dir_list_3 = wx.Button(self.notebook_2_pane_1, -1, "...")
        self.static_line_2 = wx.StaticLine(self.notebook_2_pane_1, -1)
        self.buttonEditProcessParameter = wx.Button(self.notebook_2_pane_1, -1, "Edit")
        self.buttonApplyProcessParameter = wx.Button(self.notebook_2_pane_1, -1, "Apply")
        self.radio_box_unit_cell = wx.RadioBox(self.notebook_2_pane_2, -1, "", choices=["Automatic", "User defined"], majorDimension=1, style=wx.RA_SPECIFY_ROWS)
        self.label_cell_a = wx.StaticText(self.notebook_2_pane_2, -1, "a =")
        self.text_ctrl_cell_a = wx.TextCtrl(self.notebook_2_pane_2, -1, "")
        self.label_cell_b = wx.StaticText(self.notebook_2_pane_2, -1, "b =")
        self.text_ctrl_cell_b = wx.TextCtrl(self.notebook_2_pane_2, -1, "")
        self.label_cell_c = wx.StaticText(self.notebook_2_pane_2, -1, "c =")
        self.text_ctrl_cell_c = wx.TextCtrl(self.notebook_2_pane_2, -1, "")
        self.label_cell_alpha = wx.StaticText(self.notebook_2_pane_2, -1, "alpha =")
        self.text_ctrl_cell_alpha = wx.TextCtrl(self.notebook_2_pane_2, -1, "")
        self.label_cell_beta = wx.StaticText(self.notebook_2_pane_2, -1, "beta =")
        self.text_ctrl_cell_beta = wx.TextCtrl(self.notebook_2_pane_2, -1, "")
        self.label_cell_gamma = wx.StaticText(self.notebook_2_pane_2, -1, "gamma =")
        self.text_ctrl_cell_gamma = wx.TextCtrl(self.notebook_2_pane_2, -1, "")
        self.label_sg = wx.StaticText(self.notebook_2_pane_2, -1, "Beavais Lattice")
        self.choice_sg1 = wx.Choice(self.notebook_2_pane_2, -1, choices=["Automatic selection", "Primitive Triclinic", "C Centerd Monoclinic", "Primitive Monoclinic", "F Centered Orthorhombic", "I Centered Orthorhombic", "C Centered Orthorhombic", "Primitive Orthorhombic", "I Centered Tetragonal", "Primitive Tetragonal", "Primitive Hexagonal", "Primitive Rhombohedral", "F Centered Cubic", "I Centered Cubic", "Primitive Cubic"])
        self.label_sg_num = wx.StaticText(self.notebook_2_pane_2, -1, "space group number")
        self.combo_box_sgn = wx.ComboBox(self.notebook_2_pane_2, -1, choices=["0 Auto"], style=wx.CB_DROPDOWN|wx.CB_DROPDOWN)
        self.static_line_2_copy = wx.StaticLine(self.notebook_2_pane_2, -1)
        self.buttonEditUnitcell = wx.Button(self.notebook_2_pane_2, -1, "Edit")
        self.buttonApplyUnitcell = wx.Button(self.notebook_2_pane_2, -1, "Apply")
        self.label_scaling_output_dir = wx.StaticText(self.notebook_2_pane_3, -1, "Output directory")
        self.text_ctrl_scaling_output_dir_2 = wx.TextCtrl(self.notebook_2_pane_3, -1, "The function has not yet assigned.")
        self.button_show_dir_list_4 = wx.Button(self.notebook_2_pane_3, -1, "...")
        self.static_line_6 = wx.StaticLine(self.notebook_2_pane_3, -1)
        self.label_7_reso_range = wx.StaticText(self.notebook_2_pane_3, -1, "Resolution range")
        self.label_8_reso_range = wx.StaticText(self.notebook_2_pane_3, -1, "low")
        self.text_ctrl_scale_low_resolution = wx.TextCtrl(self.notebook_2_pane_3, -1, "")
        self.label_reso_range = wx.StaticText(self.notebook_2_pane_3, -1, "high")
        self.text_ctrl_scale_high_resolution = wx.TextCtrl(self.notebook_2_pane_3, -1, "")
        self.radio_box_Merge = wx.RadioBox(self.notebook_2_pane_3, -1, "MERGE option", choices=["Merged", "No Merged"], majorDimension=0, style=wx.RA_SPECIFY_ROWS)
        self.radio_box_Fridel = wx.RadioBox(self.notebook_2_pane_3, -1, "FRIDEL'S LAW", choices=["Do not use anomalous", "Use anomalous"], majorDimension=0, style=wx.RA_SPECIFY_ROWS)
        self.static_line_6_copy = wx.StaticLine(self.notebook_2_pane_3, -1)
        self.buttonEditScaling = wx.Button(self.notebook_2_pane_3, -1, "Edit")
        self.buttonApplyScaling = wx.Button(self.notebook_2_pane_3, -1, "apply")
        self.button_Run_process = wx.Button(self.notebook_1_pane_1, -1, "Process")
        self.button_Run_scale = wx.Button(self.notebook_1_pane_1, -1, "Scale")
        self.button_Run_Pointless = wx.Button(self.notebook_1_pane_1, -1, "Pointless")
        self.static_line_4_copy_1 = wx.StaticLine(self.notebook_1_pane_1, -1, style=wx.LI_VERTICAL)
        self.button_Run_MR = wx.Button(self.notebook_1_pane_1, -1, "MR")
        self.button_Run_sad = wx.Button(self.notebook_1_pane_1, -1, "SAD")
        self.static_line_4 = wx.StaticLine(self.notebook_1_pane_1, -1)
        self.button_Stop = wx.Button(self.notebook_1_pane_1, -1, "Stop")
        self.button_Exit = wx.Button(self.notebook_1_pane_1, -1, "Exit")
        self.list_ctrl_job_list_copy = wx.ListCtrl(self.notebook_1_pane_2, -1, style=wx.LC_REPORT|wx.LC_SINGLE_SEL|wx.LC_VRULES|wx.SUNKEN_BORDER)
        self.button_ListCtrl_update = wx.Button(self.notebook_1_pane_2, -1, "update")
        self.button_ListCtrl_kill = wx.Button(self.notebook_1_pane_2, -1, "kill")
        self.label_data_directory_copy_copy_copy_1 = wx.StaticText(self.notebook_1_pane_2, -1, "Data Directory")
        self.text_ctrl_image_data_dir_compress = wx.TextCtrl(self.notebook_1_pane_2, -1, "")
        self.button_show_dir_list_5 = wx.Button(self.notebook_1_pane_2, -1, "...")
        self.button_Run_gzip = wx.Button(self.notebook_1_pane_2, -1, "gzip")
        self.label_data_directory_copy_copy_copy_1_copy = wx.StaticText(self.notebook_1_pane_2, -1, "Data Directory")
        self.text_ctrl_image_data_dir_clean_up = wx.TextCtrl(self.notebook_1_pane_2, -1, "")
        self.button_show_dir_list_6 = wx.Button(self.notebook_1_pane_2, -1, "...")
        self.button_Run_CleanUp = wx.Button(self.notebook_1_pane_2, -1, "Run")
        self.label_3_MS = wx.StaticText(self.notebook_1_pane_2, -1, "input MS")
        self.text_ctrl_MS_2 = wx.TextCtrl(self.notebook_1_pane_2, -1, "")
        self.button_MS_send_copy_copy = wx.Button(self.notebook_1_pane_2, -1, "send")
        self.button_MS_clear_copy_copy = wx.Button(self.notebook_1_pane_2, -1, "Clear All")
        self.button_MS_showlist_copy_copy = wx.Button(self.notebook_1_pane_2, -1, "show MS list")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.OnOpenJobList, id=-1)
        self.Bind(wx.EVT_MENU, self.OnSaveJobList, id=-1)
        self.Bind(wx.EVT_MENU, self.OnExit, id=-1)
        self.Bind(wx.EVT_MENU, self.OnShowSendMsg, id=-1)
        self.Bind(wx.EVT_BUTTON, self.OnFileSelect1, self.button_show_dir_list_1)
        self.Bind(wx.EVT_LIST_ITEM_SELECTED, self.OnListSelected, self.list_ctrl_job_list)
        self.Bind(wx.EVT_LIST_ITEM_ACTIVATED, self.OnDoubleClick, self.list_ctrl_job_list)
        self.Bind(wx.EVT_LIST_ITEM_RIGHT_CLICK, self.OnRightClick, self.list_ctrl_job_list)
        self.Bind(wx.EVT_BUTTON, self.On_LC_append, self.button_ListCtrl_Append)
        self.Bind(wx.EVT_BUTTON, self.On_LC_delete, self.button_ListCtrl_Delete)
        self.Bind(wx.EVT_BUTTON, self.On_LC_Clear_all, self.button_ListCtrl_clear_all)
        self.Bind(wx.EVT_BUTTON, self.On_LC_ViewInputFile, self.button_ViewInputFile)
        self.Bind(wx.EVT_BUTTON, self.On_LC_ShowLog, self.button_ViewLog)
        self.Bind(wx.EVT_BUTTON, self.On_LC_Update, self.button_ListCtrl_Update)
        self.Bind(wx.EVT_BUTTON, self.OnFileSelect2, self.button_show_dir_list_2)
        self.Bind(wx.EVT_BUTTON, self.OnFileSelect3, self.button_show_dir_list_3)
        self.Bind(wx.EVT_BUTTON, self.OnEditProcess, self.buttonEditProcessParameter)
        self.Bind(wx.EVT_BUTTON, self.OnApplyProcessParameters, self.buttonApplyProcessParameter)
        self.Bind(wx.EVT_RADIOBOX, self.OnShowCellParameter, self.radio_box_unit_cell)
        self.Bind(wx.EVT_CHOICE, self.OnShowSgNumber, self.choice_sg1)
        self.Bind(wx.EVT_BUTTON, self.OnEditUnitcell, self.buttonEditUnitcell)
        self.Bind(wx.EVT_BUTTON, self.OnApplyUnitcellParameters, self.buttonApplyUnitcell)
        self.Bind(wx.EVT_BUTTON, self.OnFileSelect, self.button_show_dir_list_4)
        self.Bind(wx.EVT_BUTTON, self.OnEditScale, self.buttonEditScaling)
        self.Bind(wx.EVT_BUTTON, self.OnApplyScalingParameters, self.buttonApplyScaling)
        self.Bind(wx.EVT_BUTTON, self.OnRunProcess, self.button_Run_process)
        self.Bind(wx.EVT_BUTTON, self.OnRunScale, self.button_Run_scale)
        self.Bind(wx.EVT_BUTTON, self.OnRunPointless, self.button_Run_Pointless)
        self.Bind(wx.EVT_BUTTON, self.OnRunMR, self.button_Run_MR)
        self.Bind(wx.EVT_BUTTON, self.OnRunSad, self.button_Run_sad)
        self.Bind(wx.EVT_BUTTON, self.OnRunStop, self.button_Stop)
        self.Bind(wx.EVT_BUTTON, self.OnExit, self.button_Exit)
        self.Bind(wx.EVT_LIST_ITEM_SELECTED, self.OnListSelected, self.list_ctrl_job_list_copy)
        self.Bind(wx.EVT_LIST_ITEM_ACTIVATED, self.OnDoubleClick, self.list_ctrl_job_list_copy)
        self.Bind(wx.EVT_LIST_ITEM_RIGHT_CLICK, self.OnRightClick, self.list_ctrl_job_list_copy)
        self.Bind(wx.EVT_BUTTON, self.On_UmicLC_update, self.button_ListCtrl_update)
        self.Bind(wx.EVT_BUTTON, self.On_UmicLC_kill, self.button_ListCtrl_kill)
        self.Bind(wx.EVT_BUTTON, self.OnFileSelect5, self.button_show_dir_list_5)
        self.Bind(wx.EVT_BUTTON, self.OnUmicRunGzip, self.button_Run_gzip)
        self.Bind(wx.EVT_BUTTON, self.OnFileSelect6, self.button_show_dir_list_6)
        self.Bind(wx.EVT_BUTTON, self.OnUmicRunCleanUp, self.button_Run_CleanUp)
        self.Bind(wx.EVT_TEXT_ENTER, self.OnSendMsg, self.text_ctrl_MS_2)
        self.Bind(wx.EVT_BUTTON, self.OnSendMsg, self.button_MS_send_copy_copy)
        self.Bind(wx.EVT_BUTTON, self.OnClearText, self.button_MS_clear_copy_copy)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainWindow.__set_properties
        self.SetTitle("SURF Main Window")
        self.frame_1_statusbar.SetStatusWidths([-1])
        # statusbar fields
        frame_1_statusbar_fields = ["frame_1_statusbar"]
        for i in range(len(frame_1_statusbar_fields)):
            self.frame_1_statusbar.SetStatusText(frame_1_statusbar_fields[i], i)
        self.frame_1_toolbar.Realize()
        self.label_prefix.SetMinSize((110, 17))
        self.label_prefix.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.text_ctrl_1.SetMinSize((300, 25))
        self.button_show_dir_list_1.SetMinSize((20, 25))
        self.button_show_dir_list_1.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.list_ctrl_job_list.SetMinSize((670,271))
        self.button_ListCtrl_Append.SetMinSize((80, 30))
        self.button_ListCtrl_Append.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.button_ListCtrl_Delete.SetMinSize((80, 30))
        self.button_ListCtrl_Delete.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.button_ListCtrl_clear_all.SetMinSize((80, 30))
        self.button_ListCtrl_clear_all.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.button_ViewInputFile.SetMinSize((80, 30))
        self.button_ViewInputFile.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.button_ViewLog.SetMinSize((80, 30))
        self.button_ViewLog.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.button_ListCtrl_Update.SetMinSize((160, 30))
        self.button_ListCtrl_Update.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.text_ctrl_LogMsg.SetMinSize((670, 130))
        self.text_ctrl_LogMsg.SetBackgroundColour(wx.Colour(233, 234, 255))
        self.text_ctrl_LogMsg.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.text_ctrl_ErrorMsg.SetMinSize((470, 130))
        self.text_ctrl_ErrorMsg.SetBackgroundColour(wx.Colour(255, 233, 236))
        self.notebook_LogMessage.SetMinSize((690, 180))
        self.notebook_LogMessage.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.label_server_name_2.SetMinSize((150, 14))
        self.label_user_name_2.SetMinSize((150, 14))
        self.label_5_copy_2_copy.SetMinSize((80, 17))
        self.label_5_copy_2_copy.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.text_ctrl_detector.Enable(False)
        self.label_6_copy_2_copy.SetMinSize((60, 17))
        self.label_6_copy_2_copy.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.text_ctrl_distance.Enable(False)
        self.label_5_copy_copy_copy.SetMinSize((80, 17))
        self.label_5_copy_copy_copy.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.text_ctrl_osc_start.Enable(False)
        self.label_6_copy_copy_copy.SetMinSize((60, 17))
        self.label_6_copy_copy_copy.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.text_ctrl_step.Enable(False)
        self.label_5_copy_1_copy_1_copy.SetMinSize((80, 17))
        self.label_5_copy_1_copy_1_copy.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.text_ctrl_beamx.Enable(False)
        self.label_6_copy_1_copy_copy.SetMinSize((60, 17))
        self.label_6_copy_1_copy_copy.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.text_ctrl_beamy.Enable(False)
        self.label_5_copy_1_copy_copy_copy.SetMinSize((80, 17))
        self.label_5_copy_1_copy_copy_copy.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.text_ctrl_wavelength.Enable(False)
        self.label_7_copy_1_copy_copy.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.choice_1_XDS_job_control.SetMinSize((300, 27))
        self.choice_1_XDS_job_control.Enable(False)
        self.choice_1_XDS_job_control.SetSelection(0)
        self.label_7_copy_2_copy.SetMinSize((110, 14))
        self.label_7_copy_2_copy.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.label_8_copy_1_copy.SetMinSize((30, 14))
        self.label_8_copy_1_copy.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.text_ctrl_integrate_start.Enable(False)
        self.label_9_copy_1_copy.SetMinSize((30, 17))
        self.label_9_copy_1_copy.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.text_ctrl_integrate_end.Enable(False)
        self.label_7_copy_copy_copy_copy_copy.SetMinSize((110, 17))
        self.label_7_copy_copy_copy_copy_copy.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.label_8_copy_copy_copy_copy_copy.SetMinSize((30, 17))
        self.label_8_copy_copy_copy_copy_copy.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.text_ctrl_low_resolution.Enable(False)
        self.label_9_copy_copy_copy_copy_copy.SetMinSize((30, 17))
        self.label_9_copy_copy_copy_copy_copy.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.text_ctrl_high_resolution.Enable(False)
        self.label_10_copy_copy.SetMinSize((110, 17))
        self.label_10_copy_copy.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.choice_BL.SetMinSize((100, 29))
        self.choice_BL.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.choice_BL.Enable(False)
        self.choice_BL.SetSelection(0)
        self.label_filename_temp_copy.SetMinSize((130, 17))
        self.label_filename_temp_copy.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.text_ctrl_XDS_filename_template.SetMinSize((200, 27))
        self.text_ctrl_XDS_filename_template.Enable(False)
        self.label_data_directory_copy_copy.SetMinSize((110, 17))
        self.label_data_directory_copy_copy.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.text_ctrl_image_data_dir.SetMinSize((250, 27))
        self.text_ctrl_image_data_dir.Enable(False)
        self.button_show_dir_list_2.SetMinSize((20, 25))
        self.button_show_dir_list_2.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.button_show_dir_list_2.Enable(False)
        self.label_data_directory_copy_copy_copy.SetMinSize((110, 17))
        self.label_data_directory_copy_copy_copy.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.text_ctrl_output_data_dir.SetMinSize((250, 27))
        self.text_ctrl_output_data_dir.Enable(False)
        self.button_show_dir_list_3.SetMinSize((20, 25))
        self.button_show_dir_list_3.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.button_show_dir_list_3.Enable(False)
        self.buttonApplyProcessParameter.Enable(False)
        self.notebook_2_pane_1.SetMinSize((473, 571))
        self.radio_box_unit_cell.Enable(False)
        self.radio_box_unit_cell.SetSelection(0)
        self.label_cell_a.SetMinSize((65, 17))
        self.label_cell_a.SetFont(wx.Font(8, wx.DEFAULT, wx.ITALIC, wx.NORMAL, 0, ""))
        self.text_ctrl_cell_a.SetMinSize((50, 27))
        self.text_ctrl_cell_a.Enable(False)
        self.label_cell_b.SetMinSize((65, 17))
        self.label_cell_b.SetFont(wx.Font(8, wx.DEFAULT, wx.ITALIC, wx.NORMAL, 0, ""))
        self.text_ctrl_cell_b.SetMinSize((50, 27))
        self.text_ctrl_cell_b.Enable(False)
        self.label_cell_c.SetMinSize((65, 17))
        self.label_cell_c.SetFont(wx.Font(8, wx.DEFAULT, wx.ITALIC, wx.NORMAL, 0, ""))
        self.text_ctrl_cell_c.SetMinSize((50, 27))
        self.text_ctrl_cell_c.Enable(False)
        self.label_cell_alpha.SetMinSize((65, 17))
        self.label_cell_alpha.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.text_ctrl_cell_alpha.SetMinSize((50, 27))
        self.text_ctrl_cell_alpha.Enable(False)
        self.label_cell_beta.SetMinSize((65, 17))
        self.label_cell_beta.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.text_ctrl_cell_beta.SetMinSize((50, 27))
        self.text_ctrl_cell_beta.Enable(False)
        self.label_cell_gamma.SetMinSize((65, 17))
        self.label_cell_gamma.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.text_ctrl_cell_gamma.SetMinSize((50, 27))
        self.text_ctrl_cell_gamma.Enable(False)
        self.label_sg.SetMinSize((140, 17))
        self.label_sg.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.choice_sg1.Enable(False)
        self.choice_sg1.SetSelection(0)
        self.label_sg_num.SetMinSize((140, 17))
        self.label_sg_num.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.combo_box_sgn.SetMinSize((100, 29))
        self.combo_box_sgn.Enable(False)
        self.combo_box_sgn.SetSelection(-1)
        self.buttonApplyUnitcell.Enable(False)
        self.label_scaling_output_dir.Enable(False)
        self.text_ctrl_scaling_output_dir_2.SetMinSize((300, 30))
        self.text_ctrl_scaling_output_dir_2.Enable(False)
        self.button_show_dir_list_4.SetMinSize((20, 25))
        self.button_show_dir_list_4.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.button_show_dir_list_4.Enable(False)
        self.label_7_reso_range.SetMinSize((110, 17))
        self.label_7_reso_range.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.label_8_reso_range.SetMinSize((30, 17))
        self.label_8_reso_range.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.text_ctrl_scale_low_resolution.Enable(False)
        self.label_reso_range.SetMinSize((30, 17))
        self.label_reso_range.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.text_ctrl_scale_high_resolution.Enable(False)
        self.radio_box_Merge.Enable(False)
        self.radio_box_Merge.SetSelection(0)
        self.radio_box_Fridel.Enable(False)
        self.radio_box_Fridel.SetSelection(0)
        self.buttonApplyScaling.Enable(False)
        self.notebook_2_pane_3.Enable(False)
        self.button_Run_process.SetMinSize((70, 40))
        self.button_Run_process.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.button_Run_scale.SetMinSize((70, 40))
        self.button_Run_scale.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.button_Run_Pointless.SetMinSize((70, 40))
        self.button_Run_Pointless.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.button_Run_MR.SetMinSize((55, 40))
        self.button_Run_MR.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.button_Run_MR.Enable(False)
        self.button_Run_sad.SetMinSize((55, 40))
        self.button_Run_sad.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.button_Run_sad.Enable(False)
        self.button_Stop.SetMinSize((95, 40))
        self.button_Stop.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.button_Exit.SetMinSize((210, 40))
        self.button_Exit.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.list_ctrl_job_list_copy.SetMinSize((670,270))
        self.button_ListCtrl_update.SetMinSize((80, 30))
        self.button_ListCtrl_update.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.button_ListCtrl_kill.SetMinSize((80, 30))
        self.button_ListCtrl_kill.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.label_data_directory_copy_copy_copy_1.SetMinSize((110, 17))
        self.label_data_directory_copy_copy_copy_1.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.text_ctrl_image_data_dir_compress.SetMinSize((400, 27))
        self.button_show_dir_list_5.SetMinSize((20, 25))
        self.button_show_dir_list_5.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.button_Run_gzip.SetMinSize((105, 40))
        self.button_Run_gzip.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.label_data_directory_copy_copy_copy_1_copy.SetMinSize((110, 17))
        self.label_data_directory_copy_copy_copy_1_copy.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.text_ctrl_image_data_dir_clean_up.SetMinSize((400, 27))
        self.button_show_dir_list_6.SetMinSize((20, 25))
        self.button_show_dir_list_6.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.button_Run_CleanUp.SetMinSize((105, 40))
        self.button_Run_CleanUp.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.label_3_MS.SetMinSize((110, 18))
        self.text_ctrl_MS_2.SetMinSize((300, 30))
        self.button_MS_send_copy_copy.SetMinSize((80, 30))
        self.button_MS_clear_copy_copy.SetMinSize((80, 30))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainWindow.__do_layout
        sizer_29 = wx.BoxSizer(wx.VERTICAL)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_9 = wx.StaticBoxSizer(self.sizer_9_staticbox, wx.HORIZONTAL)
        sizer_8_copy = wx.StaticBoxSizer(self.sizer_8_copy_staticbox, wx.HORIZONTAL)
        sizer_8 = wx.StaticBoxSizer(self.sizer_8_staticbox, wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_17_copy_copy_copy = wx.StaticBoxSizer(self.sizer_17_copy_copy_copy_staticbox, wx.VERTICAL)
        sizer_18_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_18_copy_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_30 = wx.BoxSizer(wx.VERTICAL)
        sizer_31 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_20 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_34 = wx.BoxSizer(wx.VERTICAL)
        sizer_Action = wx.StaticBoxSizer(self.sizer_Action_staticbox, wx.HORIZONTAL)
        sizer_40_copy_copy_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_39 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_43_copy_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_43 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_44 = wx.StaticBoxSizer(self.sizer_44_staticbox, wx.HORIZONTAL)
        sizer_45 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_26_copy_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_33_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_27_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_51_copy_copy_copy_copy_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_46 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_28_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_36 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11_copy_1_copy = wx.StaticBoxSizer(self.sizer_11_copy_1_copy_staticbox, wx.HORIZONTAL)
        sizer_12_copy_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_39_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_23_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_15_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_14_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_13_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_24_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_35 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_48_copy_copy = wx.StaticBoxSizer(self.sizer_48_copy_copy_staticbox, wx.HORIZONTAL)
        sizer_49_copy_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_39_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6_copy_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_53_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_51_copy_copy_copy_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_51_copy_1_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_50_copy_1_copy_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_50_copy_1_copy_1_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_50_copy_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_50_copy_2_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_32 = wx.BoxSizer(wx.VERTICAL)
        sizer_47 = wx.StaticBoxSizer(self.sizer_47_staticbox, wx.HORIZONTAL)
        sizer_48 = wx.BoxSizer(wx.VERTICAL)
        sizer_49 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_17 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_55_copy = wx.StaticBoxSizer(self.sizer_55_copy_staticbox, wx.HORIZONTAL)
        sizer_57_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_56_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_39_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_17_copy_copy = wx.StaticBoxSizer(self.sizer_17_copy_copy_staticbox, wx.VERTICAL)
        sizer_18 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_18_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_31_copy_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_34_copy_copy_copy = wx.StaticBoxSizer(self.sizer_34_copy_copy_copy_staticbox, wx.HORIZONTAL)
        sizer_35_copy_copy_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_36_copy_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_36_copy_copy_copy.Add(self.label_prefix, 0, wx.ALL, 10)
        sizer_36_copy_copy_copy.Add(self.text_ctrl_1, 0, wx.ALL, 10)
        sizer_36_copy_copy_copy.Add(self.button_show_dir_list_1, 0, wx.ALL, 10)
        sizer_36_copy_copy_copy.Add(self.static_line_3_copy_copy_copy_copy, 0, 0, 0)
        sizer_35_copy_copy_copy.Add(sizer_36_copy_copy_copy, 0, 0, 0)
        sizer_34_copy_copy_copy.Add(sizer_35_copy_copy_copy, 0, 0, 0)
        sizer_31_copy_copy_copy.Add(sizer_34_copy_copy_copy, 0, wx.LEFT|wx.RIGHT|wx.TOP, 10)
        sizer_32.Add(sizer_31_copy_copy_copy, 0, 0, 0)
        sizer_18_copy_copy.Add(self.list_ctrl_job_list, 1, wx.ALL|wx.EXPAND, 10)
        sizer_17_copy_copy.Add(sizer_18_copy_copy, 0, 0, 0)
        sizer_18.Add(self.button_ListCtrl_Append, 0, wx.ALL, 10)
        sizer_18.Add(self.button_ListCtrl_Delete, 0, wx.ALL, 10)
        sizer_18.Add(self.button_ListCtrl_clear_all, 0, wx.ALL, 10)
        sizer_18.Add(self.button_ViewInputFile, 0, wx.ALL, 10)
        sizer_18.Add(self.button_ViewLog, 0, wx.ALL, 10)
        sizer_18.Add(self.button_ListCtrl_Update, 0, wx.ALL|wx.EXPAND, 10)
        sizer_17_copy_copy.Add(sizer_18, 1, 0, 0)
        sizer_39_copy_copy.Add(sizer_17_copy_copy, 0, wx.ALL, 10)
        sizer_32.Add(sizer_39_copy_copy, 0, 0, 10)
        sizer_56_copy.Add(self.text_ctrl_LogMsg, 0, wx.ALL|wx.EXPAND, 2)
        self.notebook_2_pane_1_copy.SetSizer(sizer_56_copy)
        sizer_57_copy.Add(self.text_ctrl_ErrorMsg, 1, wx.ALL, 2)
        self.notebook_2_pane_2_copy.SetSizer(sizer_57_copy)
        self.notebook_LogMessage.AddPage(self.notebook_2_pane_1_copy, "Log Message")
        self.notebook_LogMessage.AddPage(self.notebook_2_pane_2_copy, "Error Message")
        sizer_55_copy.Add(self.notebook_LogMessage, 0, wx.ALL|wx.EXPAND, 2)
        sizer_17.Add(sizer_55_copy, 0, wx.ALL|wx.EXPAND, 10)
        sizer_32.Add(sizer_17, 0, 0, 0)
        sizer_49.Add(self.label_server_name_1, 0, wx.ALL, 10)
        sizer_49.Add(self.label_server_name_2, 0, wx.ALL, 10)
        sizer_49.Add(self.static_line_7, 0, wx.EXPAND, 0)
        sizer_49.Add(self.label_user_name_1, 0, wx.ALL, 10)
        sizer_49.Add(self.label_user_name_2, 0, wx.ALL, 10)
        sizer_48.Add(sizer_49, 1, wx.EXPAND, 0)
        sizer_47.Add(sizer_48, 1, wx.EXPAND, 0)
        sizer_32.Add(sizer_47, 0, wx.ALL|wx.EXPAND, 10)
        sizer_31.Add(sizer_32, 0, 0, 0)
        sizer_50_copy_2_copy.Add(self.label_5_copy_2_copy, 0, wx.LEFT|wx.TOP, 10)
        sizer_50_copy_2_copy.Add(self.text_ctrl_detector, 0, wx.LEFT|wx.TOP, 10)
        sizer_50_copy_2_copy.Add(self.label_6_copy_2_copy, 0, wx.LEFT|wx.TOP, 10)
        sizer_50_copy_2_copy.Add(self.text_ctrl_distance, 0, wx.LEFT|wx.TOP, 10)
        sizer_49_copy_copy.Add(sizer_50_copy_2_copy, 0, wx.EXPAND, 0)
        sizer_50_copy_copy_copy.Add(self.label_5_copy_copy_copy, 0, wx.LEFT|wx.TOP, 10)
        sizer_50_copy_copy_copy.Add(self.text_ctrl_osc_start, 0, wx.LEFT|wx.TOP, 10)
        sizer_50_copy_copy_copy.Add(self.label_6_copy_copy_copy, 0, wx.LEFT|wx.TOP, 10)
        sizer_50_copy_copy_copy.Add(self.text_ctrl_step, 0, wx.LEFT|wx.TOP, 10)
        sizer_49_copy_copy.Add(sizer_50_copy_copy_copy, 0, wx.EXPAND, 0)
        sizer_50_copy_1_copy_1_copy.Add(self.label_5_copy_1_copy_1_copy, 0, wx.LEFT|wx.TOP, 10)
        sizer_50_copy_1_copy_1_copy.Add(self.text_ctrl_beamx, 0, wx.LEFT|wx.TOP, 10)
        sizer_50_copy_1_copy_1_copy.Add(self.label_6_copy_1_copy_copy, 0, wx.LEFT|wx.TOP, 10)
        sizer_50_copy_1_copy_1_copy.Add(self.text_ctrl_beamy, 0, wx.LEFT|wx.TOP, 10)
        sizer_49_copy_copy.Add(sizer_50_copy_1_copy_1_copy, 0, wx.EXPAND, 0)
        sizer_50_copy_1_copy_copy_copy.Add(self.label_5_copy_1_copy_copy_copy, 0, wx.ALL, 10)
        sizer_50_copy_1_copy_copy_copy.Add(self.text_ctrl_wavelength, 0, wx.LEFT|wx.TOP, 10)
        sizer_49_copy_copy.Add(sizer_50_copy_1_copy_copy_copy, 0, wx.EXPAND, 0)
        sizer_11_copy_copy.Add(self.label_7_copy_1_copy_copy, 0, wx.LEFT|wx.TOP, 10)
        sizer_11_copy_copy.Add(self.choice_1_XDS_job_control, 0, wx.LEFT|wx.TOP, 10)
        sizer_49_copy_copy.Add(sizer_11_copy_copy, 0, wx.EXPAND, 0)
        sizer_51_copy_1_copy.Add(self.label_7_copy_2_copy, 0, wx.LEFT|wx.TOP, 10)
        sizer_51_copy_1_copy.Add(self.label_8_copy_1_copy, 0, wx.LEFT|wx.TOP, 10)
        sizer_51_copy_1_copy.Add(self.text_ctrl_integrate_start, 0, wx.LEFT|wx.TOP, 10)
        sizer_51_copy_1_copy.Add(self.label_9_copy_1_copy, 0, wx.LEFT|wx.TOP, 10)
        sizer_51_copy_1_copy.Add(self.text_ctrl_integrate_end, 0, wx.LEFT|wx.TOP, 10)
        sizer_49_copy_copy.Add(sizer_51_copy_1_copy, 0, wx.EXPAND, 0)
        sizer_51_copy_copy_copy_copy_copy.Add(self.label_7_copy_copy_copy_copy_copy, 0, wx.LEFT|wx.TOP, 10)
        sizer_51_copy_copy_copy_copy_copy.Add(self.label_8_copy_copy_copy_copy_copy, 0, wx.LEFT|wx.TOP, 10)
        sizer_51_copy_copy_copy_copy_copy.Add(self.text_ctrl_low_resolution, 0, wx.LEFT|wx.TOP, 10)
        sizer_51_copy_copy_copy_copy_copy.Add(self.label_9_copy_copy_copy_copy_copy, 0, wx.LEFT|wx.TOP, 10)
        sizer_51_copy_copy_copy_copy_copy.Add(self.text_ctrl_high_resolution, 0, wx.LEFT|wx.TOP, 10)
        sizer_49_copy_copy.Add(sizer_51_copy_copy_copy_copy_copy, 0, wx.EXPAND, 0)
        sizer_53_copy_copy.Add(self.label_10_copy_copy, 0, wx.LEFT|wx.TOP, 10)
        sizer_53_copy_copy.Add(self.choice_BL, 0, wx.LEFT|wx.TOP, 10)
        sizer_49_copy_copy.Add(sizer_53_copy_copy, 0, wx.EXPAND, 0)
        sizer_7_copy.Add(self.label_filename_temp_copy, 0, wx.ALL, 10)
        sizer_7_copy.Add(self.text_ctrl_XDS_filename_template, 0, wx.ALL, 10)
        sizer_49_copy_copy.Add(sizer_7_copy, 0, wx.EXPAND, 0)
        sizer_6_copy_copy.Add(self.label_data_directory_copy_copy, 0, wx.LEFT|wx.TOP, 10)
        sizer_6_copy_copy.Add(self.text_ctrl_image_data_dir, 0, wx.LEFT|wx.TOP, 10)
        sizer_6_copy_copy.Add(self.button_show_dir_list_2, 0, wx.ALL, 10)
        sizer_49_copy_copy.Add(sizer_6_copy_copy, 0, wx.EXPAND, 0)
        sizer_6_copy_copy_copy.Add(self.label_data_directory_copy_copy_copy, 0, wx.LEFT|wx.TOP, 10)
        sizer_6_copy_copy_copy.Add(self.text_ctrl_output_data_dir, 0, wx.LEFT|wx.TOP, 10)
        sizer_6_copy_copy_copy.Add(self.button_show_dir_list_3, 0, wx.ALL, 10)
        sizer_49_copy_copy.Add(sizer_6_copy_copy_copy, 0, wx.EXPAND, 0)
        sizer_49_copy_copy.Add(self.static_line_2, 0, wx.TOP|wx.BOTTOM|wx.EXPAND, 10)
        sizer_39_copy.Add(self.buttonEditProcessParameter, 1, wx.ALL, 10)
        sizer_39_copy.Add(self.buttonApplyProcessParameter, 1, wx.ALL, 10)
        sizer_49_copy_copy.Add(sizer_39_copy, 0, wx.EXPAND, 0)
        sizer_48_copy_copy.Add(sizer_49_copy_copy, 0, 0, 0)
        sizer_35.Add(sizer_48_copy_copy, 0, wx.ALL, 10)
        self.notebook_2_pane_1.SetSizer(sizer_35)
        sizer_24_copy_copy.Add(self.radio_box_unit_cell, 0, wx.ALL, 10)
        sizer_12_copy_copy.Add(sizer_24_copy_copy, 0, 0, 0)
        sizer_13_copy_copy.Add(self.label_cell_a, 0, wx.LEFT|wx.TOP, 10)
        sizer_13_copy_copy.Add(self.text_ctrl_cell_a, 0, wx.TOP, 10)
        sizer_13_copy_copy.Add(self.label_cell_b, 0, wx.LEFT|wx.TOP, 10)
        sizer_13_copy_copy.Add(self.text_ctrl_cell_b, 0, wx.TOP, 10)
        sizer_13_copy_copy.Add(self.label_cell_c, 0, wx.LEFT|wx.TOP, 10)
        sizer_13_copy_copy.Add(self.text_ctrl_cell_c, 0, wx.RIGHT|wx.TOP, 10)
        sizer_12_copy_copy.Add(sizer_13_copy_copy, 0, 0, 0)
        sizer_14_copy_copy.Add(self.label_cell_alpha, 0, wx.LEFT|wx.TOP, 10)
        sizer_14_copy_copy.Add(self.text_ctrl_cell_alpha, 0, wx.TOP, 10)
        sizer_14_copy_copy.Add(self.label_cell_beta, 0, wx.LEFT|wx.TOP, 10)
        sizer_14_copy_copy.Add(self.text_ctrl_cell_beta, 0, wx.TOP, 10)
        sizer_14_copy_copy.Add(self.label_cell_gamma, 0, wx.LEFT|wx.TOP, 10)
        sizer_14_copy_copy.Add(self.text_ctrl_cell_gamma, 0, wx.RIGHT|wx.TOP, 10)
        sizer_12_copy_copy.Add(sizer_14_copy_copy, 0, wx.EXPAND, 0)
        sizer_15_copy_copy.Add(self.label_sg, 0, wx.ALL, 10)
        sizer_15_copy_copy.Add(self.choice_sg1, 0, wx.ALL, 10)
        sizer_12_copy_copy.Add(sizer_15_copy_copy, 0, 0, 0)
        sizer_23_copy_copy.Add(self.label_sg_num, 0, wx.ALL, 10)
        sizer_23_copy_copy.Add(self.combo_box_sgn, 0, wx.ALL, 10)
        sizer_12_copy_copy.Add(sizer_23_copy_copy, 0, 0, 0)
        sizer_12_copy_copy.Add(self.static_line_2_copy, 0, wx.TOP|wx.BOTTOM|wx.EXPAND, 10)
        sizer_39_copy_1.Add(self.buttonEditUnitcell, 1, wx.ALL, 10)
        sizer_39_copy_1.Add(self.buttonApplyUnitcell, 1, wx.ALL, 10)
        sizer_12_copy_copy.Add(sizer_39_copy_1, 1, wx.EXPAND, 0)
        sizer_11_copy_1_copy.Add(sizer_12_copy_copy, 0, 0, 0)
        sizer_36.Add(sizer_11_copy_1_copy, 0, wx.ALL, 10)
        self.notebook_2_pane_2.SetSizer(sizer_36)
        sizer_28_copy_copy.Add(self.label_scaling_output_dir, 0, wx.ALL, 10)
        sizer_26_copy_copy.Add(sizer_28_copy_copy, 0, wx.EXPAND, 0)
        sizer_46.Add(self.text_ctrl_scaling_output_dir_2, 0, wx.ALL, 10)
        sizer_46.Add(self.button_show_dir_list_4, 0, wx.ALL, 10)
        sizer_26_copy_copy.Add(sizer_46, 0, wx.EXPAND, 0)
        sizer_26_copy_copy.Add(self.static_line_6, 0, wx.EXPAND, 0)
        sizer_51_copy_copy_copy_copy_copy_copy.Add(self.label_7_reso_range, 0, wx.LEFT|wx.TOP, 10)
        sizer_51_copy_copy_copy_copy_copy_copy.Add(self.label_8_reso_range, 0, wx.LEFT|wx.TOP, 10)
        sizer_51_copy_copy_copy_copy_copy_copy.Add(self.text_ctrl_scale_low_resolution, 0, wx.LEFT|wx.TOP, 10)
        sizer_51_copy_copy_copy_copy_copy_copy.Add(self.label_reso_range, 0, wx.LEFT|wx.TOP, 10)
        sizer_51_copy_copy_copy_copy_copy_copy.Add(self.text_ctrl_scale_high_resolution, 0, wx.LEFT|wx.TOP, 10)
        sizer_26_copy_copy.Add(sizer_51_copy_copy_copy_copy_copy_copy, 0, wx.EXPAND, 0)
        sizer_27_copy_copy.Add(self.radio_box_Merge, 1, wx.ALL, 10)
        sizer_27_copy_copy.Add(self.radio_box_Fridel, 1, wx.ALL, 10)
        sizer_26_copy_copy.Add(sizer_27_copy_copy, 0, wx.EXPAND, 0)
        sizer_26_copy_copy.Add(self.static_line_6_copy, 0, wx.EXPAND, 0)
        sizer_33_copy_copy.Add(self.buttonEditScaling, 1, wx.ALL, 10)
        sizer_33_copy_copy.Add(self.buttonApplyScaling, 1, wx.ALL, 10)
        sizer_26_copy_copy.Add(sizer_33_copy_copy, 0, wx.EXPAND, 0)
        sizer_45.Add(sizer_26_copy_copy, 0, wx.EXPAND, 0)
        sizer_44.Add(sizer_45, 0, wx.ALL, 10)
        sizer_43.Add(sizer_44, 0, wx.ALL, 10)
        self.notebook_2_pane_3.SetSizer(sizer_43)
        self.notebook_2.AddPage(self.notebook_2_pane_1, "Parameter")
        self.notebook_2.AddPage(self.notebook_2_pane_2, "Unit Cell")
        self.notebook_2.AddPage(self.notebook_2_pane_3, "Scaling")
        sizer_34.Add(self.notebook_2, 0, wx.LEFT|wx.RIGHT|wx.TOP, 30)
        sizer_43_copy_copy_copy.Add(self.button_Run_process, 1, wx.ALL, 10)
        sizer_43_copy_copy_copy.Add(self.button_Run_scale, 1, wx.ALL, 10)
        sizer_43_copy_copy_copy.Add(self.button_Run_Pointless, 1, wx.ALL, 10)
        sizer_43_copy_copy_copy.Add(self.static_line_4_copy_1, 0, wx.EXPAND, 0)
        sizer_43_copy_copy_copy.Add(self.button_Run_MR, 0, wx.ALL, 10)
        sizer_43_copy_copy_copy.Add(self.button_Run_sad, 0, wx.ALL, 10)
        sizer_40_copy_copy_copy.Add(sizer_43_copy_copy_copy, 0, 0, 0)
        sizer_40_copy_copy_copy.Add(self.static_line_4, 0, wx.EXPAND, 0)
        sizer_39.Add(self.button_Stop, 0, wx.ALL, 10)
        sizer_39.Add(self.button_Exit, 1, wx.ALL|wx.EXPAND, 10)
        sizer_40_copy_copy_copy.Add(sizer_39, 0, 0, 0)
        sizer_Action.Add(sizer_40_copy_copy_copy, 0, wx.BOTTOM, 10)
        sizer_34.Add(sizer_Action, 0, wx.ALL|wx.ALIGN_RIGHT, 30)
        sizer_20.Add(sizer_34, 0, 0, 0)
        sizer_31.Add(sizer_20, 1, 0, 0)
        sizer_30.Add(sizer_31, 0, wx.EXPAND, 0)
        self.notebook_1_pane_1.SetSizer(sizer_30)
        sizer_18_copy_copy_copy.Add(self.list_ctrl_job_list_copy, 1, wx.ALL|wx.EXPAND, 10)
        sizer_17_copy_copy_copy.Add(sizer_18_copy_copy_copy, 0, 0, 0)
        sizer_18_copy.Add(self.button_ListCtrl_update, 0, wx.ALL, 10)
        sizer_18_copy.Add(self.button_ListCtrl_kill, 0, wx.ALL, 10)
        sizer_17_copy_copy_copy.Add(sizer_18_copy, 1, wx.ALIGN_RIGHT, 0)
        sizer_7.Add(sizer_17_copy_copy_copy, 0, wx.ALL, 10)
        sizer_6.Add(sizer_7, 0, wx.EXPAND, 0)
        sizer_8.Add(self.label_data_directory_copy_copy_copy_1, 0, wx.LEFT|wx.TOP, 10)
        sizer_8.Add(self.text_ctrl_image_data_dir_compress, 0, wx.LEFT|wx.TOP, 10)
        sizer_8.Add(self.button_show_dir_list_5, 0, wx.ALL, 10)
        sizer_8.Add(self.button_Run_gzip, 0, wx.ALL, 10)
        sizer_6.Add(sizer_8, 0, wx.ALL, 10)
        sizer_8_copy.Add(self.label_data_directory_copy_copy_copy_1_copy, 0, wx.LEFT|wx.TOP, 10)
        sizer_8_copy.Add(self.text_ctrl_image_data_dir_clean_up, 0, wx.LEFT|wx.TOP, 10)
        sizer_8_copy.Add(self.button_show_dir_list_6, 0, wx.ALL, 10)
        sizer_8_copy.Add(self.button_Run_CleanUp, 0, wx.ALL, 10)
        sizer_6.Add(sizer_8_copy, 0, wx.ALL, 10)
        sizer_9.Add(self.label_3_MS, 0, wx.ALL, 10)
        sizer_9.Add(self.text_ctrl_MS_2, 0, wx.TOP|wx.BOTTOM, 10)
        sizer_9.Add(self.button_MS_send_copy_copy, 0, wx.TOP, 10)
        sizer_9.Add(self.button_MS_clear_copy_copy, 0, wx.TOP, 10)
        sizer_9.Add(self.button_MS_showlist_copy_copy, 0, wx.LEFT|wx.TOP, 10)
        sizer_6.Add(sizer_9, 0, wx.ALL, 10)
        self.notebook_1_pane_2.SetSizer(sizer_6)
        self.notebook_1.AddPage(self.notebook_1_pane_1, "Data analysis")
        self.notebook_1.AddPage(self.notebook_1_pane_2, "Umi cluster control")
        sizer_29.Add(self.notebook_1, 0, 0, 0)
        self.SetSizer(sizer_29)
        sizer_29.Fit(self)
        sizer_29.SetSizeHints(self)
        self.Layout()
        self.Centre()
        # end wxGlade

    def OnOpenJobList(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnOpenJobList' not implemented!"
        event.Skip()

    def OnSaveJobList(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnSaveJobList' not implemented!"
        event.Skip()

    def OnExit(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnExit' not implemented!"
        event.Skip()

    def OnShowSendMsg(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnShowSendMsg' not implemented!"
        event.Skip()

    def OnFileSelect1(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnFileSelect1' not implemented!"
        event.Skip()

    def OnListSelected(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnListSelected' not implemented!"
        event.Skip()

    def OnDoubleClick(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnDoubleClick' not implemented!"
        event.Skip()

    def OnRightClick(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnRightClick' not implemented!"
        event.Skip()

    def On_LC_append(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `On_LC_append' not implemented!"
        event.Skip()

    def On_LC_delete(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `On_LC_delete' not implemented!"
        event.Skip()

    def On_LC_Clear_all(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `On_LC_Clear_all' not implemented!"
        event.Skip()

    def On_LC_ViewInputFile(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `On_LC_ViewInputFile' not implemented!"
        event.Skip()

    def On_LC_ShowLog(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `On_LC_ShowLog' not implemented!"
        event.Skip()

    def On_LC_Update(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `On_LC_Update' not implemented!"
        event.Skip()

    def OnFileSelect2(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnFileSelect2' not implemented!"
        event.Skip()

    def OnFileSelect3(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnFileSelect3' not implemented!"
        event.Skip()

    def OnEditProcess(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnEditProcess' not implemented!"
        event.Skip()

    def OnApplyProcessParameters(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnApplyProcessParameters' not implemented!"
        event.Skip()

    def OnShowCellParameter(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnShowCellParameter' not implemented!"
        event.Skip()

    def OnShowSgNumber(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnShowSgNumber' not implemented!"
        event.Skip()

    def OnEditUnitcell(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnEditUnitcell' not implemented!"
        event.Skip()

    def OnApplyUnitcellParameters(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnApplyUnitcellParameters' not implemented!"
        event.Skip()

    def OnFileSelect(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnFileSelect' not implemented!"
        event.Skip()

    def OnEditScale(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnEditScale' not implemented!"
        event.Skip()

    def OnApplyScalingParameters(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnApplyScalingParameters' not implemented!"
        event.Skip()

    def OnRunProcess(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnRunProcess' not implemented!"
        event.Skip()

    def OnRunScale(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnRunScale' not implemented!"
        event.Skip()

    def OnRunPointless(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnRunPointless' not implemented!"
        event.Skip()

    def OnRunMR(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnRunMR' not implemented!"
        event.Skip()

    def OnRunSad(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnRunSad' not implemented!"
        event.Skip()

    def OnRunStop(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnRunStop' not implemented!"
        event.Skip()

    def On_UmicLC_update(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `On_UmicLC_update' not implemented!"
        event.Skip()

    def On_UmicLC_kill(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `On_UmicLC_kill' not implemented!"
        event.Skip()

    def OnFileSelect5(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnFileSelect5' not implemented!"
        event.Skip()

    def OnUmicRunGzip(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnUmicRunGzip' not implemented!"
        event.Skip()

    def OnFileSelect6(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnFileSelect6' not implemented!"
        event.Skip()

    def OnUmicRunCleanUp(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnUmicRunCleanUp' not implemented!"
        event.Skip()

    def OnSendMsg(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnSendMsg' not implemented!"
        event.Skip()

    def OnClearText(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnClearText' not implemented!"
        event.Skip()

# end of class MainWindow


class Dialog_Error_Message(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Dialog_Error_Message.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_error_message = wx.StaticText(self, -1, "Message")
        self.static_line_5 = wx.StaticLine(self, -1)
        self.ok_button = wx.Button(self, -1, "OK")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnClose, self.ok_button)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Dialog_Error_Message.__set_properties
        self.SetTitle("Error Dialog")
        self.label_error_message.SetMinSize((300, 100))
        self.ok_button.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Dialog_Error_Message.__do_layout
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(self.label_error_message, 0, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 10)
        sizer_2.Add(self.static_line_5, 0, wx.EXPAND, 0)
        sizer_2.Add(self.ok_button, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 10)
        sizer_1.Add(sizer_2, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def OnClose(self, event): # wxGlade: Dialog_Error_Message.<event_handler>
        print "Event handler `OnClose' not implemented!"
        event.Skip()

# end of class Dialog_Error_Message


class Dialog_Selection(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Dialog_Selection.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_1_copy = wx.StaticText(self, -1, "Select a data set")
        self.list_box_1 = wx.ListBox(self, -1, choices=[], style=wx.LB_SINGLE)
        self.static_line_3 = wx.StaticLine(self, -1)
        self.label_1 = wx.StaticText(self, -1, "Output directory")
        self.text_ctrl_2 = wx.TextCtrl(self, -1, "")
        self.button_1 = wx.Button(self, -1, "...")
        self.static_line_3_copy = wx.StaticLine(self, -1)
        self.button_2 = wx.Button(self, -1, "apply")
        self.button_2_copy = wx.Button(self, -1, "cancel")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_LISTBOX_DCLICK, self.OnListFocased, self.list_box_1)
        self.Bind(wx.EVT_LISTBOX, self.OnListFocased, self.list_box_1)
        self.Bind(wx.EVT_BUTTON, self.OnFileSelect, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.OnApply, self.button_2)
        self.Bind(wx.EVT_BUTTON, self.OnClose, self.button_2_copy)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Dialog_Selection.__set_properties
        self.SetTitle("Selection")
        self.list_box_1.SetMinSize((300, 100))
        self.text_ctrl_2.SetMinSize((330, 28))
        self.button_1.SetMinSize((35, 30))
        self.button_2.SetMinSize((189,40))
        self.button_2.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.button_2_copy.SetMinSize((190, 40))
        self.button_2_copy.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Dialog_Selection.__do_layout
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4.Add(self.label_1_copy, 0, wx.ALL, 10)
        sizer_4.Add(self.list_box_1, 0, wx.ALL|wx.EXPAND, 5)
        sizer_4.Add(self.static_line_3, 0, wx.TOP|wx.BOTTOM|wx.EXPAND, 10)
        sizer_10.Add(self.label_1, 0, wx.ALL, 10)
        sizer_4.Add(sizer_10, 0, wx.EXPAND, 0)
        sizer_11.Add(self.text_ctrl_2, 0, wx.ALL|wx.EXPAND, 10)
        sizer_11.Add(self.button_1, 0, wx.ALL|wx.EXPAND, 10)
        sizer_4.Add(sizer_11, 0, wx.EXPAND, 0)
        sizer_4.Add(self.static_line_3_copy, 0, wx.TOP|wx.BOTTOM|wx.EXPAND, 10)
        sizer_5.Add(self.button_2, 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 10)
        sizer_5.Add(self.button_2_copy, 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 10)
        sizer_4.Add(sizer_5, 0, wx.EXPAND, 0)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_3)
        sizer_3.Fit(self)
        self.Layout()
        # end wxGlade

    def OnListFocased(self, event): # wxGlade: Dialog_Selection.<event_handler>
        print "Event handler `OnListFocased' not implemented!"
        event.Skip()

    def OnFileSelect(self, event): # wxGlade: Dialog_Selection.<event_handler>
        print "Event handler `OnFileSelect' not implemented!"
        event.Skip()

    def OnApply(self, event): # wxGlade: Dialog_Selection.<event_handler>
        print "Event handler `OnApply' not implemented!"
        event.Skip()

    def OnClose(self, event): # wxGlade: Dialog_Selection.<event_handler>
        print "Event handler `OnClose' not implemented!"
        event.Skip()

# end of class Dialog_Selection


class Dialog_LogView(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Dialog_LogView.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.text_ctrl_log = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY|wx.HSCROLL|wx.TE_RICH)
        self.button_4 = wx.Button(self, -1, "Close")
        self.button_3 = wx.Button(self, -1, "Update")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnClose, self.button_4)
        self.Bind(wx.EVT_BUTTON, self.OnLogViewUpdate, self.button_3)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Dialog_LogView.__set_properties
        self.SetTitle("Log View")
        self.text_ctrl_log.SetMinSize((800, 400))
        self.text_ctrl_log.SetFont(wx.Font(8, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, ""))
        self.button_3.SetMinSize((150, 34))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Dialog_LogView.__do_layout
        sizer_16 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_19 = wx.BoxSizer(wx.VERTICAL)
        sizer_22 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_19.Add(self.text_ctrl_log, 0, wx.ALL, 5)
        sizer_22.Add(self.button_4, 0, wx.ALL, 10)
        sizer_22.Add(self.button_3, 0, wx.ALL|wx.ALIGN_RIGHT, 10)
        sizer_19.Add(sizer_22, 1, wx.EXPAND, 0)
        sizer_16.Add(sizer_19, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_16)
        sizer_16.Fit(self)
        self.Layout()
        # end wxGlade

    def OnClose(self, event): # wxGlade: Dialog_LogView.<event_handler>
        print "Event handler `OnClose' not implemented!"
        event.Skip()

    def OnLogViewUpdate(self, event): # wxGlade: Dialog_LogView.<event_handler>
        print "Event handler `OnLogViewUpdate' not implemented!"
        event.Skip()

# end of class Dialog_LogView


class Dialog_LogGraph(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Dialog_LogGraph.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER|wx.THICK_FRAME
        wx.Dialog.__init__(self, *args, **kwds)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Dialog_LogGraph.__set_properties
        self.SetTitle("LogGraph")
        self.SetSize((565, 689))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Dialog_LogGraph.__do_layout
        self.Layout()
        # end wxGlade

# end of class Dialog_LogGraph


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MainWindow(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
