#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Mon Nov 15 02:29:02 2010

import wx
import sys
import math
sys.path.append("/isilon/BL32XU/BLsoft/PPPP/")
from Gonio import *
from Colli import *
from File import *
from ScheduleBSS import *


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.notebook_1 = wx.Notebook(self, -1, style=0)
        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, -1)
        self.sizer_5_staticbox = wx.StaticBox(self.notebook_1_pane_1, -1, "")
        self.sizer_8_staticbox = wx.StaticBox(self.notebook_1_pane_1, -1, "")
        self.label_1 = wx.StaticText(self.notebook_1_pane_1, -1, "Data directory", style=wx.ALIGN_CENTRE)
        self.direBox = wx.TextCtrl(self.notebook_1_pane_1, -1, "/isilon/blusers/target/target/")
        self.label_1_copy = wx.StaticText(self.notebook_1_pane_1, -1, "File prefix", style=wx.ALIGN_CENTRE)
        self.prefixBox = wx.TextCtrl(self.notebook_1_pane_1, -1, "prefix")
        self.label_2 = wx.StaticText(self.notebook_1_pane_1, -1, "Serial offset", style=wx.ALIGN_CENTRE)
        self.serialBox = wx.TextCtrl(self.notebook_1_pane_1, -1, "1")
        self.text111 = wx.StaticText(self.notebook_1_pane_1, -1, "Beam size", style=wx.ALIGN_CENTRE)
        self.label_8 = wx.StaticText(self.notebook_1_pane_1, -1, "Vertical")
        self.bsVertBox = wx.TextCtrl(self.notebook_1_pane_1, -1, "10.0")
        self.label_8_copy = wx.StaticText(self.notebook_1_pane_1, -1, "[um]")
        self.label_8_copy_1 = wx.StaticText(self.notebook_1_pane_1, -1, "Horizontal")
        self.bsHoriBox = wx.TextCtrl(self.notebook_1_pane_1, -1, "10.0")
        self.label_8_copy_copy = wx.StaticText(self.notebook_1_pane_1, -1, "[um]")
        self.label_3 = wx.StaticText(self.notebook_1_pane_1, -1, "Oscillation from ")
        self.oscStartBox = wx.TextCtrl(self.notebook_1_pane_1, -1, "0.0", style=wx.TE_CENTRE)
        self.label_4_copy = wx.StaticText(self.notebook_1_pane_1, -1, "to")
        self.oscEndBox = wx.TextCtrl(self.notebook_1_pane_1, -1, "1.0", style=wx.TE_CENTRE)
        self.label_4_copy_copy = wx.StaticText(self.notebook_1_pane_1, -1, "by")
        self.oscStepBox = wx.TextCtrl(self.notebook_1_pane_1, -1, "1.0", style=wx.TE_CENTRE)
        self.label_4_copy_copy_copy = wx.StaticText(self.notebook_1_pane_1, -1, "[deg]")
        self.setCurrentPhiButton = wx.Button(self.notebook_1_pane_1, -1, "Set Curr Phi")
        self.label_3_copy = wx.StaticText(self.notebook_1_pane_1, -1, "Exposure time", style=wx.ALIGN_CENTRE)
        self.exptimeBox = wx.TextCtrl(self.notebook_1_pane_1, -1, "1.0", style=wx.TE_CENTRE)
        self.label_4_copy_copy_1 = wx.StaticText(self.notebook_1_pane_1, -1, "[sec]")
        self.wlBox = wx.StaticText(self.notebook_1_pane_1, -1, "Wavelength")
        self.wavelenBox = wx.TextCtrl(self.notebook_1_pane_1, -1, "1.0000", style=wx.TE_CENTRE)
        self.label_4_copy_copy_1_copy = wx.StaticText(self.notebook_1_pane_1, -1, "[A]")
        self.expBox = wx.StaticText(self.notebook_1_pane_1, -1, "Camera length")
        self.camelenBox = wx.TextCtrl(self.notebook_1_pane_1, -1, "300.0", style=wx.TE_CENTRE)
        self.label_4_copy_copy_1_copy_copy = wx.StaticText(self.notebook_1_pane_1, -1, "[mm]")
        self.label_3_copy_copy = wx.StaticText(self.notebook_1_pane_1, -1, "Attenuator")
        self.attPullDown = wx.ComboBox(self.notebook_1_pane_1, -1, choices=["none", "100", "200", "300", "400", "500", "600", "700", "800", "900", "1000", "1500", "3000", "6000"], style=wx.CB_DROPDOWN)
        self.label_4 = wx.StaticText(self.notebook_1_pane_1, -1, "[um]")
        self.checkButton = wx.Button(self.notebook_1_pane_1, -1, "Check")
        self.label_9 = wx.StaticText(self.notebook_1_pane_1, -1, "Simulation")
        self.label_10 = wx.StaticText(self.notebook_1_pane_1, -1, "Edge resolution", style=wx.ALIGN_CENTRE)
        self.edgeResolSimuBox = wx.TextCtrl(self.notebook_1_pane_1, -1, "", style=wx.TE_READONLY)
        self.label_11 = wx.StaticText(self.notebook_1_pane_1, -1, "[A]")
        self.label_10_copy_copy = wx.StaticText(self.notebook_1_pane_1, -1, "Att. Factor")
        self.attSimuBox = wx.TextCtrl(self.notebook_1_pane_1, -1, "", style=wx.TE_READONLY)
        self.label_11_copy_copy = wx.StaticText(self.notebook_1_pane_1, -1, "[%]")
        self.notebook_1_pane_2 = wx.Panel(self.notebook_1, -1)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.pushSetPhi, self.setCurrentPhiButton)
        self.Bind(wx.EVT_BUTTON, self.pushCheck, self.checkButton)
        # end wxGlade

# end of class MyFrame
        host = '172.24.242.41'
        port = 10101
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.connect((host,port))

        self.gonio=Gonio(s)
        self.scheFile=ScheduleBSS()

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("KUMA system")
        self.label_1.SetMinSize((120, 18))
        self.direBox.SetMinSize((500, 35))
        self.label_1_copy.SetMinSize((120, 18))
        self.prefixBox.SetMinSize((250, 35))
        self.serialBox.SetMinSize((100, 35))
        self.text111.SetMinSize((62, 18))
        self.bsVertBox.SetMinSize((100, 35))
        self.bsHoriBox.SetMinSize((100, 35))
        self.label_3.SetMinSize((130, 18))
        self.label_3_copy.SetMinSize((130, 18))
        self.wlBox.SetMinSize((130, 18))
        self.expBox.SetMinSize((130, 18))
        self.label_3_copy_copy.SetMinSize((130, 18))
        self.attPullDown.SetMinSize((150, 27))
        self.attPullDown.SetSelection(10)
        self.label_4.SetMinSize((29, 18))
        self.label_9.SetMinSize((150, 23))
        self.label_9.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_10.SetMinSize((120, 18))
        self.edgeResolSimuBox.SetBackgroundColour(wx.Colour(228, 228, 228))
        self.label_10_copy_copy.SetMinSize((120, 18))
        self.attSimuBox.SetBackgroundColour(wx.Colour(186, 186, 186))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.StaticBoxSizer(self.sizer_5_staticbox, wx.HORIZONTAL)
        sizer_8 = wx.StaticBoxSizer(self.sizer_8_staticbox, wx.HORIZONTAL)
        sizer_10 = wx.BoxSizer(wx.VERTICAL)
        sizer_11_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11_copy_1_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_7_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7_copy_copy_1_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7_copy_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4.Add(self.label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_4.Add(self.direBox, 0, wx.ADJUST_MINSIZE, 0)
        sizer_3.Add(sizer_4, 0, wx.EXPAND, 0)
        sizer_4_copy.Add(self.label_1_copy, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_4_copy.Add(self.prefixBox, 0, wx.ADJUST_MINSIZE, 0)
        sizer_4_copy.Add((50, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_4_copy.Add(self.label_2, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ADJUST_MINSIZE, 0)
        sizer_4_copy.Add(self.serialBox, 0, wx.ADJUST_MINSIZE, 0)
        sizer_3.Add(sizer_4_copy, 0, wx.EXPAND, 0)
        sizer_4_copy_copy.Add(self.text111, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_4_copy_copy.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_4_copy_copy.Add(self.label_8, 0, wx.ADJUST_MINSIZE, 0)
        sizer_4_copy_copy.Add(self.bsVertBox, 0, wx.ADJUST_MINSIZE, 0)
        sizer_4_copy_copy.Add(self.label_8_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_4_copy_copy.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_4_copy_copy.Add(self.label_8_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_4_copy_copy.Add(self.bsHoriBox, 0, wx.ADJUST_MINSIZE, 0)
        sizer_4_copy_copy.Add(self.label_8_copy_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_3.Add(sizer_4_copy_copy, 0, wx.EXPAND, 0)
        sizer_6.Add((20, 25), 0, wx.ADJUST_MINSIZE, 0)
        sizer_7.Add(self.label_3, 0, wx.ADJUST_MINSIZE, 0)
        sizer_7.Add(self.oscStartBox, 0, wx.ADJUST_MINSIZE, 0)
        sizer_7.Add(self.label_4_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_7.Add(self.oscEndBox, 0, wx.ADJUST_MINSIZE, 0)
        sizer_7.Add(self.label_4_copy_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_7.Add(self.oscStepBox, 0, wx.ADJUST_MINSIZE, 0)
        sizer_7.Add(self.label_4_copy_copy_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_7.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_7.Add(self.setCurrentPhiButton, 0, wx.ADJUST_MINSIZE, 0)
        sizer_6.Add(sizer_7, 1, wx.EXPAND, 0)
        sizer_7_copy.Add(self.label_3_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_7_copy.Add(self.exptimeBox, 0, wx.ADJUST_MINSIZE, 0)
        sizer_7_copy.Add(self.label_4_copy_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_6.Add(sizer_7_copy, 1, wx.EXPAND, 0)
        sizer_7_copy_copy_1.Add(self.wlBox, 0, wx.ADJUST_MINSIZE, 0)
        sizer_7_copy_copy_1.Add(self.wavelenBox, 0, wx.ADJUST_MINSIZE, 0)
        sizer_7_copy_copy_1.Add(self.label_4_copy_copy_1_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_6.Add(sizer_7_copy_copy_1, 1, wx.EXPAND, 0)
        sizer_7_copy_copy_1_copy.Add(self.expBox, 0, wx.ADJUST_MINSIZE, 0)
        sizer_7_copy_copy_1_copy.Add(self.camelenBox, 0, wx.ADJUST_MINSIZE, 0)
        sizer_7_copy_copy_1_copy.Add(self.label_4_copy_copy_1_copy_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_6.Add(sizer_7_copy_copy_1_copy, 1, wx.EXPAND, 0)
        sizer_7_copy_copy.Add(self.label_3_copy_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_7_copy_copy.Add(self.attPullDown, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_7_copy_copy.Add(self.label_4, 0, wx.ADJUST_MINSIZE, 0)
        sizer_7_copy_copy.Add((50, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_7_copy_copy.Add(self.checkButton, 0, wx.ADJUST_MINSIZE, 0)
        sizer_6.Add(sizer_7_copy_copy, 1, wx.EXPAND, 0)
        sizer_5.Add(sizer_6, 1, wx.EXPAND, 0)
        sizer_10.Add(self.label_9, 0, wx.ADJUST_MINSIZE, 0)
        sizer_11.Add(self.label_10, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_11.Add(self.edgeResolSimuBox, 0, wx.ADJUST_MINSIZE, 0)
        sizer_11.Add(self.label_11, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10.Add(sizer_11, 1, wx.EXPAND, 0)
        sizer_11_copy_1_copy.Add(self.label_10_copy_copy, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ADJUST_MINSIZE, 0)
        sizer_11_copy_1_copy.Add(self.attSimuBox, 0, wx.ADJUST_MINSIZE, 0)
        sizer_11_copy_1_copy.Add(self.label_11_copy_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10.Add(sizer_11_copy_1_copy, 1, wx.EXPAND, 0)
        sizer_10.Add(sizer_11_copy_1, 1, wx.EXPAND, 0)
        sizer_8.Add(sizer_10, 1, wx.EXPAND, 0)
        sizer_5.Add(sizer_8, 0, wx.EXPAND, 0)
        sizer_3.Add(sizer_5, 0, wx.EXPAND, 0)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_3_copy, 1, wx.EXPAND, 0)
        self.notebook_1_pane_1.SetSizer(sizer_2)
        self.notebook_1.AddPage(self.notebook_1_pane_1, "condition")
        self.notebook_1.AddPage(self.notebook_1_pane_2, "App")
        sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def pushSetPhi(self, event): # wxGlade: MyFrame.<event_handler>
	curr=self.gonio.getPhi()
	startstr="%8.2f"%curr
	endstr="%8.2f"%(curr+1.0)
        self.oscStartBox.SetValue(startstr)
        self.oscEndBox.SetValue(endstr)

    def pushCheck(self, event): # wxGlade: MyFrame.<event_handler>
        dist=float(self.camelenBox.GetValue())
        wavelength=float(self.wavelenBox.GetValue())

	twotheta=math.atan((225.0/2.0)/dist)
	theta=twotheta/2.0
	maxd=wavelength/2.0/math.sin(theta)
	maxdstr="%8.2f"%maxd
        self.edgeResolSimuBox.SetValue(maxdstr)
	#print dist,wavelength

# end of class MyFrame


if __name__ == "__main__":
    kuma = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, -1, "")
    kuma.SetTopWindow(frame_1)
    frame_1.Show()
    kuma.MainLoop()
