#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# generated by wxGlade 0.4.1 on Sat Apr 24 22:09:27 2010

import wx
from SetBeamSize import *

class BeamSizeChanger(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: BeamSizeChanger.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.label_3 = wx.StaticText(self, -1, "Set Beamsize to")
        self.inputSize = wx.TextCtrl(self, -1, "")
        self.label_4 = wx.StaticText(self, -1, "[um]")
        self.button_1 = wx.Button(self, -1, "Go")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: BeamSizeChanger.__set_properties
        self.SetTitle("Frame3")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: BeamSizeChanger.__do_layout
        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8.Add(self.label_3, 0, 0, 0)
        sizer_8.Add(self.inputSize, 0, 0, 0)
        sizer_8.Add(self.label_4, 0, 0, 0)
        sizer_8.Add(self.button_1, 0, 0, 0)
        sizer_7.Add(sizer_8, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_7)
        sizer_7.Fit(self)
        self.Layout()
        # end wxGlade

    def setButton(self, event): # wxGlade: BeamSizeChanger.<event_handler>
        size=float(self.inputSize.GetValue())
	flag=sbs.setSize(size)

	if flag<0:
		print "Error"

if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_2 = BeamSizeChanger(None, -1, "")
    app.SetTopWindow(frame_2)
    frame_2.Show()
    app.MainLoop()

