#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Mon Oct  8 14:00:22 2012

import wx
import os,sys,socket

# begin wxGlade: extracode
sys.path.append("/isilon/BL32XU/BLsoft/PPPP/")
from Zoom import *
from CoaxPint import *
from ConfigFile import *
# end wxGlade

class Centering(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Centering.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.label_2 = wx.StaticText(self, -1, "Fit Pint")
        self.upstreamButton = wx.Button(self, -1, "GO")

	# Configure file ~/PPPP/bl32xu.conf
	self.conf=ConfigFile()

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.pressUSbutton, self.upstreamButton)
        # end wxGlade

    def readConfig(self):
        self.pint_x130=int(self.conf.getCondition2("COAX","x130_pint")) #[pulse]
        self.pint_x64=int(self.conf.getCondition2("COAX","x64_pint")) #[pulse]
        self.pint_x30=int(self.conf.getCondition2("COAX","x30_pint")) #[pulse]
        self.pint_x14=int(self.conf.getCondition2("COAX","x14_pint")) #[pulse]

    def __set_properties(self):
        # begin wxGlade: Centering.__set_properties
        self.SetTitle("kokokuma")
        self.label_2.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.upstreamButton.SetMinSize((100, 100))
        self.upstreamButton.SetFont(wx.Font(17, wx.ROMAN, wx.SLANT, wx.BOLD, 0, ""))
        # end wxGlade

        # kuntaro classes
        host = '172.24.242.41'
        port = 10101
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.connect((host,port))
	self.zoom=Zoom(s)
	self.coaxpint=CoaxPint(s)

    def __do_layout(self):
        # begin wxGlade: Centering.__do_layout
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_5_copy.Add(self.label_2, 0, 0, 0)
        sizer_5_copy.Add(self.upstreamButton, 0, 0, 0)
        sizer_1.Add(sizer_5_copy, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

### TO BE MODIFIED
    def pressUSbutton(self, event): # wxGlade: Centering.<event_handler>
	zoom_value=self.zoom.getPosition()

	# Read config file information
        self.readConfig()

        self.pint_x130=int(self.conf.getCondition2("COAX","x130_pint")) #[pulse]
        self.pint_x64=int(self.conf.getCondition2("COAX","x64_pint")) #[pulse]
        self.pint_x30=int(self.conf.getCondition2("COAX","x30_pint")) #[pulse]
        self.pint_x14=int(self.conf.getCondition2("COAX","x14_pint")) #[pulse]

	# x130
	if zoom_value==0:
		coax_x_pls=self.pint_x130
	# x64
	if zoom_value==-16000:
		coax_x_pls=self.pint_x64
	# x30
	if zoom_value==-32000:
		coax_x_pls=self.pint_x30
	# x14
	if zoom_value==-38000:
		coax_x_pls=self.pint_x14
	# MOVE
	print "Move to ",coax_x_pls," [pls]"
	self.coaxpint.move(coax_x_pls)

if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_2 = Centering(None, -1, "")
    app.SetTopWindow(frame_2)
    frame_2.Show()
    app.MainLoop()
