#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sat Apr 24 16:30:33 2010

import wx
from Gonio import *

# begin wxGlade: extracode
# end wxGlade

class GonioCenter(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: GonioCenter.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.leftButton = wx.Button(self, -1, "Left")
        self.panel_3 = wx.Panel(self, -1)
        self.panel_5 = wx.Panel(self, -1)
        self.label_1 = wx.StaticText(self, -1, "Position")
        self.upButton = wx.Button(self, -1, "Up")
        self.positionInput = wx.TextCtrl(self, -1, "")
        self.label_9 = wx.StaticText(self, -1, "[um]")
        self.downButton = wx.Button(self, -1, "Down")
        self.rightButton = wx.Button(self, -1, "Right")
        self.panel_11 = wx.Panel(self, -1)
        self.label_5 = wx.StaticText(self, -1, "Phi rotation")
        self.rotPlusButton = wx.Button(self, -1, "+")
        self.inputDegree = wx.TextCtrl(self, -1, "")
        self.label_10 = wx.StaticText(self, -1, "[deg]")
        self.rotMinusButton = wx.Button(self, -1, "-")
        self.label_7 = wx.StaticText(self, -1, "Current Status")
        self.currPhi = wx.TextCtrl(self, -1, "", style=wx.TE_READONLY|wx.HSCROLL)
        self.label_8 = wx.StaticText(self, -1, "[deg.]")
        self.panel_10 = wx.Panel(self, -1)
        self.label_2_copy = wx.StaticText(self, -1, "Pint")
        self.upstreamButton = wx.Button(self, -1, "Upstream")
        self.pintInput = wx.TextCtrl(self, -1, "")
        self.downstreamButton = wx.Button(self, -1, "Downstream")
        self.label_4 = wx.StaticText(self, -1, "[um]")
        self.panel_13 = wx.Panel(self, -1)
        self.panel_12 = wx.Panel(self, -1)

	# TEST
        host = '172.24.242.41'
        port = 10101
        self.s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self.s.connect((host,port))
	self.gonio=Gonio(self.s,3)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.pressLbutton, self.leftButton)
        self.Bind(wx.EVT_BUTTON, self.pressUbutton, self.upButton)
        self.Bind(wx.EVT_BUTTON, self.pressDbutton, self.downButton)
        self.Bind(wx.EVT_BUTTON, self.pressRbutton, self.rightButton)
        self.Bind(wx.EVT_BUTTON, self.rotatePlus, self.rotPlusButton)
        self.Bind(wx.EVT_BUTTON, self.rotateMinus, self.rotMinusButton)
        self.Bind(wx.EVT_BUTTON, self.pressUSbutton, self.upstreamButton)
        self.Bind(wx.EVT_BUTTON, self.pressDSbutton, self.downstreamButton)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: GonioCenter.__set_properties
        self.SetTitle("Centering Tool for BL32XU")
        self.rotPlusButton.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.rotMinusButton.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.currPhi.SetBackgroundColour(wx.Colour(166, 166, 166))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: GonioCenter.__do_layout
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5_copy_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_22 = wx.BoxSizer(wx.VERTICAL)
        sizer_21 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_13 = wx.BoxSizer(wx.VERTICAL)
        sizer_14 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_18 = wx.BoxSizer(wx.VERTICAL)
        sizer_20 = wx.BoxSizer(wx.VERTICAL)
        sizer_17 = wx.BoxSizer(wx.VERTICAL)
        sizer_19 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_16 = wx.BoxSizer(wx.VERTICAL)
        sizer_15 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_4.Add((20, 50), 0, 0, 0)
        sizer_4.Add((20, 40), 0, 0, 0)
        sizer_4.Add(self.leftButton, 0, 0, 0)
        sizer_4.Add(self.panel_3, 1, wx.EXPAND, 0)
        sizer_4.Add(self.panel_5, 1, wx.EXPAND, 0)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_6.Add(self.label_1, 0, 0, 0)
        sizer_6.Add(self.upButton, 0, 0, 0)
        sizer_15.Add((20, 40), 0, 0, 0)
        sizer_15.Add(self.positionInput, 0, 0, 0)
        sizer_7.Add(sizer_15, 1, wx.EXPAND, 0)
        sizer_16.Add((20, 20), 0, 0, 0)
        sizer_16.Add(self.label_9, 0, 0, 0)
        sizer_7.Add(sizer_16, 1, wx.EXPAND, 0)
        sizer_6.Add(sizer_7, 1, wx.EXPAND, 0)
        sizer_6.Add(self.downButton, 0, 0, 0)
        sizer_3.Add(sizer_6, 1, wx.EXPAND, 0)
        sizer_5.Add((20, 50), 0, 0, 0)
        sizer_5.Add((20, 40), 0, 0, 0)
        sizer_5.Add(self.rightButton, 0, 0, 0)
        sizer_5.Add(self.panel_11, 1, wx.EXPAND, 0)
        sizer_3.Add(sizer_5, 1, wx.EXPAND, 0)
        sizer_3.Add((20, 123), 0, 0, 0)
        sizer_2.Add(self.label_5, 0, 0, 0)
        sizer_2.Add(self.rotPlusButton, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_17.Add((20, 20), 0, 0, 0)
        sizer_19.Add(self.inputDegree, 0, 0, 0)
        sizer_19.Add((20, 20), 0, 0, 0)
        sizer_17.Add(sizer_19, 1, wx.EXPAND, 0)
        sizer_9.Add(sizer_17, 1, wx.EXPAND, 0)
        sizer_18.Add((20, 20), 0, 0, 0)
        sizer_20.Add(self.label_10, 0, 0, 0)
        sizer_20.Add((20, 20), 0, 0, 0)
        sizer_18.Add(sizer_20, 1, wx.EXPAND, 0)
        sizer_9.Add(sizer_18, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_9, 1, wx.EXPAND, 0)
        sizer_2.Add(self.rotMinusButton, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_13.Add(self.label_7, 0, 0, 0)
        sizer_14.Add(self.currPhi, 0, 0, 0)
        sizer_14.Add(self.label_8, 0, 0, 0)
        sizer_13.Add(sizer_14, 1, wx.EXPAND, 0)
        sizer_13.Add(self.panel_10, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_13, 1, wx.EXPAND, 0)
        sizer_3.Add(sizer_2, 1, wx.EXPAND, 0)
        sizer_3.Add((20, 20), 0, 0, 0)
        sizer_5_copy_1.Add(self.label_2_copy, 0, 0, 0)
        sizer_5_copy_1.Add(self.upstreamButton, 0, 0, 0)
        sizer_21.Add((20, 20), 0, 0, 0)
        sizer_21.Add(self.pintInput, 0, 0, 0)
        sizer_21.Add(self.downstreamButton, 0, 0, 0)
        sizer_11.Add(sizer_21, 1, wx.EXPAND, 0)
        sizer_22.Add((20, 20), 0, 0, 0)
        sizer_22.Add(self.label_4, 0, 0, 0)
        sizer_22.Add(self.panel_13, 1, wx.EXPAND, 0)
        sizer_11.Add(sizer_22, 1, wx.EXPAND, 0)
        sizer_5_copy_1.Add(sizer_11, 1, wx.EXPAND, 0)
        sizer_5_copy_1.Add(self.panel_12, 1, wx.EXPAND, 0)
        sizer_3.Add(sizer_5_copy_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_3)
        sizer_3.Fit(self)
        self.Layout()
        # end wxGlade


    def pressUbutton(self, event): # wxGlade: GonioCenter.<event_handler>
        dist=float(self.positionInput.GetValue())
	print "Gonio xz to %8.3f um"%dist
	self.gonio.moveUpDown(dist)

    def pressDbutton(self, event): # wxGlade: GonioCenter.<event_handler>
        dist=-float(self.positionInput.GetValue())
	print "Gonio xz to %8.3f um"%dist
	self.gonio.moveUpDown(dist)

    def pressLbutton(self, event): # wxGlade: GonioCenter.<event_handler>
        dist=-float(self.positionInput.GetValue())
	print "Gonio y move %8.3f um"%dist
	self.gonio.moveTrans(dist)

    def pressRbutton(self, event): # wxGlade: GonioCenter.<event_handler>
        dist=float(self.positionInput.GetValue())
	print "Gonio y move %8.3f um"%dist
	self.gonio.moveTrans(dist)

    def pressUSbutton(self, event): # wxGlade: GonioCenter.<event_handler>
        dist=float(self.pintInput.GetValue())
	print dist
	self.gonio.movePint(dist)

    def pressDSbutton(self, event): # wxGlade: GonioCenter.<event_handler>
        dist=-float(self.pintInput.GetValue())
	print dist
	self.gonio.movePint(dist)

    def rotatePlus(self, event): # wxGlade: GonioCenter.<event_handler>
        rot_ang=float(self.inputDegree.GetValue())
	self.gonio.rotatePhiRelative(rot_ang)

	curr_ang_text="%8.2f"%self.gonio.getPhi()
	self.currPhi.SetValue(curr_ang_text)

    def rotateMinus(self, event): # wxGlade: GonioCenter.<event_handler>
        rot_ang=-float(self.inputDegree.GetValue())
	self.gonio.rotatePhiRelative(rot_ang)

	curr_ang_text="%8.2f"%self.gonio.getPhi()
	self.currPhi.SetValue(curr_ang_text)

# end of class GonioCenter

if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_2 = GonioCenter(None, -1, "")
    app.SetTopWindow(frame_2)
    frame_2.Show()
    app.MainLoop()
