#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sat Apr 24 14:03:01 2010

import wx

# begin wxGlade: extracode
# end wxGlade

class GonioCenter(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: GonioCenter.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, -1)
        self.leftButton = wx.Button(self, -1, "Left")
        self.panel_3 = wx.Panel(self, -1)
        self.label_1 = wx.StaticText(self, -1, "Position")
        self.upButton = wx.Button(self, -1, "Up")
        self.positionInput = wx.TextCtrl(self, -1, "")
        self.label_3 = wx.StaticText(self, -1, "[um]")
        self.downButton = wx.Button(self, -1, "Down")
        self.panel_2 = wx.Panel(self, -1)
        self.rightButton = wx.Button(self, -1, "Right")
        self.panel_4 = wx.Panel(self, -1)
        self.panel_5 = wx.Panel(self, -1)
        self.label_2 = wx.StaticText(self, -1, "Pint")
        self.upstreamButton = wx.Button(self, -1, "Upstream")
        self.pintInput = wx.TextCtrl(self, -1, "")
        self.label_4 = wx.StaticText(self, -1, "[um]")
        self.downstreamButton = wx.Button(self, -1, "Downstream")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.pressLbutton, self.leftButton)
        self.Bind(wx.EVT_BUTTON, self.pressUbutton, self.upButton)
        self.Bind(wx.EVT_BUTTON, self.pressDbutton, self.downButton)
        self.Bind(wx.EVT_BUTTON, self.pressRbutton, self.rightButton)
        self.Bind(wx.EVT_BUTTON, self.pressUSbutton, self.upstreamButton)
        self.Bind(wx.EVT_BUTTON, self.pressDSbutton, self.downstreamButton)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: GonioCenter.__set_properties
        self.SetTitle("frame_2")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: GonioCenter.__do_layout
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5_copy_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_5_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_4.Add((20, 20), 0, 0, 0)
        sizer_4.Add(self.panel_1, 1, wx.EXPAND, 0)
        sizer_4.Add(self.leftButton, 0, 0, 0)
        sizer_4.Add(self.panel_3, 1, wx.EXPAND, 0)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_6.Add(self.label_1, 0, 0, 0)
        sizer_6.Add(self.upButton, 0, 0, 0)
        sizer_7.Add(self.positionInput, 0, 0, 0)
        sizer_7.Add(self.label_3, 0, 0, 0)
        sizer_6.Add(sizer_7, 1, wx.EXPAND, 0)
        sizer_6.Add(self.downButton, 0, 0, 0)
        sizer_3.Add(sizer_6, 1, wx.EXPAND, 0)
        sizer_5.Add((20, 20), 0, 0, 0)
        sizer_5.Add(self.panel_2, 1, wx.EXPAND, 0)
        sizer_5.Add(self.rightButton, 0, 0, 0)
        sizer_5.Add(self.panel_4, 1, wx.EXPAND, 0)
        sizer_3.Add(sizer_5, 1, wx.EXPAND, 0)
        sizer_3.Add(self.panel_5, 1, wx.EXPAND, 0)
        sizer_5_copy.Add(self.label_2, 0, 0, 0)
        sizer_5_copy.Add(self.upstreamButton, 0, 0, 0)
        sizer_8.Add(self.pintInput, 0, 0, 0)
        sizer_8.Add(self.label_4, 0, 0, 0)
        sizer_5_copy.Add(sizer_8, 1, wx.EXPAND, 0)
        sizer_5_copy.Add(self.downstreamButton, 0, 0, 0)
        sizer_3.Add(sizer_5_copy, 1, wx.EXPAND, 0)
        sizer_3.Add(sizer_5_copy_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_3)
        sizer_3.Fit(self)
        self.Layout()
        # end wxGlade

    def pressLbutton(self, event): # wxGlade: GonioCenter.<event_handler>
        print "Event handler `pressLbutton' not implemented!"
        event.Skip()

    def pressUbutton(self, event): # wxGlade: GonioCenter.<event_handler>
        print "Event handler `pressUbutton' not implemented!"
        event.Skip()

    def pressDbutton(self, event): # wxGlade: GonioCenter.<event_handler>
        print "Event handler `pressDbutton' not implemented!"
        event.Skip()

    def pressRbutton(self, event): # wxGlade: GonioCenter.<event_handler>
        print "Event handler `pressRbutton' not implemented!"
        event.Skip()

    def pressUSbutton(self, event): # wxGlade: GonioCenter.<event_handler>
        print "Event handler `pressUSbutton' not implemented!"
        event.Skip()

    def pressDSbutton(self, event): # wxGlade: GonioCenter.<event_handler>
        print "Event handler `pressDSbutton' not implemented!"
        event.Skip()

# end of class GonioCenter


class Centering(wx.Frame):
    def __init__(self, *args, **kwds):
        # content of this block not found: did you rename this class?
        pass

    def __set_properties(self):
        # content of this block not found: did you rename this class?
        pass

    def __do_layout(self):
        # content of this block not found: did you rename this class?
        pass

    def pressLbutton(self, event): # wxGlade: Centering.<event_handler>
        dist=float(self.positionInput.GetValue())
	print dist

    def pressUbutton(self, event): # wxGlade: Centering.<event_handler>
        dist=float(self.positionInput.GetValue())

    def pressDbutton(self, event): # wxGlade: Centering.<event_handler>
        dist=float(self.positionInput.GetValue())

    def pressRbutton(self, event): # wxGlade: Centering.<event_handler>
        dist=float(self.positionInput.GetValue())

    def pressUSbutton(self, event): # wxGlade: Centering.<event_handler>
        dist=float(self.pintInput.GetValue())

    def pressDSbutton(self, event): # wxGlade: Centering.<event_handler>
        dist=float(self.pintInput.GetValue())

# end of class Centering


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = (None, -1, "")
    app.SetTopWindow(frame_1)
    Centering.Show()
    app.MainLoop()
