# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Wed Apr 21 01:42:06 2010

import wx

from Colli import *

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class BLcntl(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: BLcntl.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.InfoCollimator = wx.StaticText(self, -1, "Gonio Pint", style=wx.ALIGN_CENTRE)
        self.text_ctrl_1 = wx.TextCtrl(self, -1, "")
        self.unit = wx.StaticText(self, -1, "[um]")
        self.buttonPlus = Gonio(self, -1, "+")
        self.buttonMinus = wx.Button(self, -1, "-")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: BLcntl.__set_properties
        self.SetTitle("frame_1")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: BLcntl.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(10, 10, 0, 0)
        grid_sizer_1.Add(self.InfoCollimator, 0, 0, 0)
        grid_sizer_1.Add(self.text_ctrl_1, 0, 0, 0)
        grid_sizer_1.Add(self.unit, 0, 0, 0)
        grid_sizer_1.Add(self.buttonPlus, 0, 0, 0)
        grid_sizer_1.Add(self.buttonMinus, 0, 0, 0)
        sizer_2.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        self.Layout()
        # end wxGlade

# end of class BLcntl


