# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Wed Apr 21 03:07:37 2010

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class MyFrame1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame1.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.text_ctrl_2 = wx.TextCtrl(self, -1, "")
        self.button_3 = wx.Button(self, -1, "button_3")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.get_text, self.button_3)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame1.__set_properties
        self.SetTitle("frame_2")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame1.__do_layout
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6.Add(self.text_ctrl_2, 0, 0, 0)
        sizer_6.Add(self.button_3, 0, 0, 0)
        sizer_5.Add(sizer_6, 1, wx.EXPAND, 0)
        sizer_4.Add(sizer_5, 1, wx.EXPAND, 0)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_3)
        sizer_3.Fit(self)
        self.Layout()
        # end wxGlade

    def get_text(self, event): # wxGlade: MyFrame1.<event_handler>
        print "Event handler `get_text' not implemented!"
        event.Skip()

# end of class MyFrame1


