#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Fri Apr 23 12:16:28 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class SimpleBL(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SimpleBL.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.label_1 = wx.StaticText(self, -1, "Change energy to")
        self.inputEnergy = wx.TextCtrl(self, -1, "")
        self.label_2 = wx.StaticText(self, -1, "keV")
        self.goButton = wx.Button(self, -1, "GO")
        self.logEchange = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE|wx.HSCROLL)
        self.label_3 = wx.StaticText(self, -1, "Delta theta1")
        self.tuneButton = wx.Button(self, -1, "tune")
        self.logTune = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.doChange, self.goButton)
        self.Bind(wx.EVT_BUTTON, self.tune, self.tuneButton)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: SimpleBL.__set_properties
        self.SetTitle("frame_1")
        self.label_1.SetFont(wx.Font(18, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.label_2.SetFont(wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.goButton.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.label_3.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.tuneButton.SetFont(wx.Font(18, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: SimpleBL.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4.Add(self.label_1, 0, 0, 0)
        sizer_4.Add(self.inputEnergy, 0, 0, 0)
        sizer_4.Add(self.label_2, 0, 0, 0)
        sizer_4.Add(self.goButton, 0, 0, 0)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_3.Add(self.logEchange, 0, wx.EXPAND, 0)
        sizer_5.Add(self.label_3, 0, 0, 0)
        sizer_6.Add(self.tuneButton, 0, 0, 0)
        sizer_6.Add(self.logTune, 0, wx.EXPAND, 0)
        sizer_5.Add(sizer_6, 1, wx.EXPAND, 0)
        sizer_3.Add(sizer_5, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def doChange(self, event): # wxGlade: SimpleBL.<event_handler>
        en_str=self.inputEnergy.GetValue()
	print en_str

    def tune(self, event): # wxGlade: SimpleBL.<event_handler>
	print "test"

# end of class SimpleBL


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = SimpleBL(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
