#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sun Jul 18 12:11:12 2010

import wx

# begin wxGlade: extracode
# end wxGlade

import sys
sys.path.append("/isilon/BL32XU/BLsoft/PPPP/")
from Colli import *
from Light import *
from BS import *
from Cryo import *
from Zoom import *

class Fuckin(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Fuckin.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.button_1 = wx.Button(self, -1, "Push to evacuate")
        self.button_1_copy = wx.Button(self, -1, "Push to experiment")
        self.button_1_copy_copy = wx.Button(self, -1, "Push to centering")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.pushEvacuate, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.pushExperiment, self.button_1_copy)
        self.Bind(wx.EVT_BUTTON, self.pushCentering, self.button_1_copy_copy)
        # end wxGlade
        # kuntaro definition
        host = '172.24.242.41'
        port = 10101
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.connect((host,port))

        self.bs=BS(s)
        self.colli=Colli(s)
        self.light=Light(s)
        self.cryo=Cryo(s)
        self.zoom=Zoom(s)

    def __set_properties(self):
        # begin wxGlade: Fuckin.__set_properties
        self.SetTitle("Fucking Tenose")
        self.button_1.SetMinSize((150, 80))
        self.button_1_copy.SetMinSize((150, 80))
        self.button_1_copy_copy.SetMinSize((150, 80))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Fuckin.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(self.button_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_2.Add(self.button_1_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_2.Add(self.button_1_copy_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def pushEvacuate(self, event): # wxGlade: Fuckin.<event_handler>
        self.bs.go(-70000)
        self.colli.go(-70000)
        self.zoom.go(-48000)
        self.cryo.go(500)
        self.light.off()

    def pushExperiment(self, event): # wxGlade: Fuckin.<event_handler>
        self.bs.go(0)
        self.colli.go(0)
        self.cryo.go(250)
        self.light.off()

    def pushCentering(self, event): # wxGlade: Fuckin.<event_handler>
        self.colli.go(-20000)
        self.bs.go(-20000)
        self.zoom.go(-48000)
        self.cryo.go(250)
        self.light.on()

# end of class Fuckin


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = Fuckin(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
