#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Thu Mar  3 00:52:39 2011

import wx
import os
from AnaBestLog import *
# begin wxGlade: extracode
# end wxGlade

class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.CAPTION|wx.CLOSE_BOX|wx.MINIMIZE_BOX|wx.MAXIMIZE_BOX|wx.STAY_ON_TOP|wx.SYSTEM_MENU|wx.RESIZE_BORDER|wx.CLIP_CHILDREN
        wx.Frame.__init__(self, *args, **kwds)
        self.notebook_1 = wx.Notebook(self, -1, style=0)
        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, -1)
        self.label_4 = wx.StaticText(self.notebook_1_pane_1, -1, "Image file")
        self.filenameBox = wx.TextCtrl(self.notebook_1_pane_1, -1, "", style=wx.TE_READONLY)
        self.button_1_copy = wx.Button(self.notebook_1_pane_1, -1, "Choose")
        self.button_1 = wx.Button(self.notebook_1_pane_1, -1, "Show strategy")
        self.label_1 = wx.StaticText(self.notebook_1_pane_1, -1, "Resol.")
        self.resolBox = wx.TextCtrl(self.notebook_1_pane_1, -1, "", style=wx.TE_CENTRE)
        self.label_1_copy = wx.StaticText(self.notebook_1_pane_1, -1, "[A]")
        self.label_1_copy_1 = wx.StaticText(self.notebook_1_pane_1, -1, "Exp. Time")
        self.exptimeBox = wx.TextCtrl(self.notebook_1_pane_1, -1, "", style=wx.TE_CENTRE)
        self.label_1_copy_copy = wx.StaticText(self.notebook_1_pane_1, -1, "[sec]")
        self.label_1_copy_1_copy = wx.StaticText(self.notebook_1_pane_1, -1, "Oscillation")
        self.startphiBox = wx.TextCtrl(self.notebook_1_pane_1, -1, "", style=wx.TE_CENTRE)
        self.label_2 = wx.StaticText(self.notebook_1_pane_1, -1, "-")
        self.endphiBox = wx.TextCtrl(self.notebook_1_pane_1, -1, "", style=wx.TE_CENTRE)
        self.label_3 = wx.StaticText(self.notebook_1_pane_1, -1, "[by]")
        self.phiwidthBox = wx.TextCtrl(self.notebook_1_pane_1, -1, "", style=wx.TE_CENTRE)
        self.label_3_copy_1 = wx.StaticText(self.notebook_1_pane_1, -1, "[deg]")
        self.label_1_copy_1_copy_copy = wx.StaticText(self.notebook_1_pane_1, -1, "Al for 1sec.")
        self.attBox = wx.TextCtrl(self.notebook_1_pane_1, -1, "", style=wx.TE_CENTRE)
        self.label_3_copy = wx.StaticText(self.notebook_1_pane_1, -1, "[um]")
        self.label_1_copy_1_copy_copy_copy = wx.StaticText(self.notebook_1_pane_1, -1, "Distance")
        self.distBox = wx.TextCtrl(self.notebook_1_pane_1, -1, "", style=wx.TE_CENTRE)
        self.label_3_copy_copy = wx.StaticText(self.notebook_1_pane_1, -1, "[mm]")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.pushChoose, self.button_1_copy)
        self.Bind(wx.EVT_BUTTON, self.yarude, self.button_1)
        # end wxGlade

	self.filemenu=wx.Menu()
	self.menuOpen=self.filemenu.Append(wx.ID_OPEN,"&Open","open project")
	self.menuExit=self.filemenu.Append(wx.ID_EXIT,"&EXIT","exit project")

	self.Bind(wx.EVT_MENU,self.OnOpen,self.menuOpen)
	self.Bind(wx.EVT_MENU,self.OnExit,self.menuExit)

	self.menuBar=wx.MenuBar()
	self.menuBar.Append(self.filemenu,"&File")
	self.SetMenuBar(self.menuBar)

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame_1")
        self.label_4.SetMinSize((100, 18))
        self.label_4.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.filenameBox.SetMinSize((350, 24))
        self.label_1.SetMinSize((120, 18))
        self.resolBox.SetMinSize((150, 28))
        self.label_1_copy_1.SetMinSize((120, 18))
        self.exptimeBox.SetMinSize((150, 28))
        self.label_1_copy_1_copy.SetMinSize((120, 18))
        self.startphiBox.SetMinSize((100, 28))
        self.endphiBox.SetMinSize((100, 28))
        self.phiwidthBox.SetMinSize((100, 28))
        self.label_1_copy_1_copy_copy.SetMinSize((120, 18))
        self.attBox.SetMinSize((100, 28))
        self.label_1_copy_1_copy_copy_copy.SetMinSize((120, 18))
        self.distBox.SetMinSize((100, 28))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_5_copy_copy_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5_copy_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_5_copy_1, 1, wx.ALL|wx.EXPAND, 0)
        sizer_6.Add(self.label_4, 0, wx.ADJUST_MINSIZE, 0)
        sizer_6.Add(self.filenameBox, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_2.Add(sizer_6, 1, wx.EXPAND, 0)
        sizer_4.Add(self.button_1_copy, 0, 0, 0)
        sizer_4.Add(self.button_1, 0, 0, 0)
        sizer_2.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_5.Add(self.label_1, 0, 0, 0)
        sizer_5.Add(self.resolBox, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_5.Add(self.label_1_copy, 0, 0, 0)
        sizer_2.Add(sizer_5, 1, wx.ALL|wx.EXPAND, 0)
        sizer_5_copy.Add(self.label_1_copy_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_5_copy.Add(self.exptimeBox, 0, wx.ALL, 0)
        sizer_5_copy.Add(self.label_1_copy_copy, 0, 0, 0)
        sizer_2.Add(sizer_5_copy, 1, wx.ALL|wx.EXPAND, 0)
        sizer_5_copy_copy.Add(self.label_1_copy_1_copy, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_5_copy_copy.Add(self.startphiBox, 0, wx.ALL, 0)
        sizer_5_copy_copy.Add(self.label_2, 0, 0, 0)
        sizer_5_copy_copy.Add(self.endphiBox, 0, wx.ALL, 0)
        sizer_5_copy_copy.Add(self.label_3, 0, 0, 0)
        sizer_5_copy_copy.Add(self.phiwidthBox, 0, wx.ALL, 0)
        sizer_5_copy_copy.Add(self.label_3_copy_1, 0, 0, 0)
        sizer_2.Add(sizer_5_copy_copy, 1, wx.ALL|wx.EXPAND, 0)
        sizer_5_copy_copy_copy.Add(self.label_1_copy_1_copy_copy, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_5_copy_copy_copy.Add(self.attBox, 0, wx.ALL, 0)
        sizer_5_copy_copy_copy.Add(self.label_3_copy, 0, 0, 0)
        sizer_2.Add(sizer_5_copy_copy_copy, 1, wx.ALL|wx.EXPAND, 0)
        sizer_5_copy_copy_copy_copy.Add(self.label_1_copy_1_copy_copy_copy, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_5_copy_copy_copy_copy.Add(self.distBox, 0, wx.ALL, 0)
        sizer_5_copy_copy_copy_copy.Add(self.label_3_copy_copy, 0, 0, 0)
        sizer_2.Add(sizer_5_copy_copy_copy_copy, 1, wx.ALL|wx.EXPAND, 0)
        self.notebook_1_pane_1.SetSizer(sizer_2)
        self.notebook_1.AddPage(self.notebook_1_pane_1, "Strategy")
        sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        self.Centre()
        # end wxGlade

    def yarude(self, event): # wxGlade: MyFrame.<event_handler>
        bl=AnaBestLog(self.logfile)
        dict=bl.getDict()
	self.resolBox.SetValue("%5.2f"%dict["RESLIM"])
	self.exptimeBox.SetValue("%5.1f"%dict["EXPTIME"])
	self.startphiBox.SetValue("%5.1f"%dict["STARTPHI"])
	self.endphiBox.SetValue("%5.1f"%dict["ENDPHI"])
	self.attBox.SetValue("%5.0f"%dict["AL"])
	self.distBox.SetValue("%5.0f"%dict["CL"])
	self.phiwidthBox.SetValue("%5.1f"% dict["WIDTH"])

    def pushChoose(self, event): # wxGlade: MyFrame.<event_handler>
        self.dirName = ''
        dialog = wx.FileDialog(self, "Choose a file", self.dirName, "", "*.*", wx.OPEN)
        if dialog.ShowModal() == wx.ID_OK:
            self.fileName = dialog.GetFilename()
            self.dirName = dialog.GetDirectory()
	    self.logfile="%s/%s"%(self.dirName,self.fileName)
	    self.filenameBox.SetValue(self.logfile)

# end of class MyFrame
    def OnOpen(self,e):
        self.dirName = ''
        dialog = wx.FileDialog(self, "Choose a file", self.dirName, "", "*.*", wx.OPEN)
        if dialog.ShowModal() == wx.ID_OK:
            self.fileName = dialog.GetFilename()
            self.dirName = dialog.GetDirectory()
	    print self.fileName,self.dirName
	    self.logfile="%s/%s"%(self.dirName,self.fileName)
	    self.filenameBox.SetValue(self.logfile)
        dialog.Destroy()

    def OnExit(self,e):
        dialog = wx.MessageDialog( self, "exit?", "Messege title", wx.OK)
        dialog.ShowModal()
        dialog.Destroy()
        self.Close()

if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
