#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Mon Jun 20 14:04:59 2011

import wx

# begin wxGlade: extracode
# end wxGlade

import sys
sys.path.append("/isilon/BL32XU/BLsoft/PPPP/")
from DiffscanLog import *

class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.CAPTION|wx.CLOSE_BOX|wx.MINIMIZE_BOX|wx.MAXIMIZE_BOX|wx.STAY_ON_TOP|wx.SYSTEM_MENU|wx.RESIZE_BORDER|wx.CLIP_CHILDREN
        wx.Frame.__init__(self, *args, **kwds)
        self.notebook_1 = wx.Notebook(self, -1, style=0)
        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, -1)
        self.label_4 = wx.StaticText(self.notebook_1_pane_1, -1, "diffscan.log\n")
        self.filenameBox = wx.TextCtrl(self.notebook_1_pane_1, -1, "", style=wx.TE_READONLY)
        self.button_1_copy = wx.Button(self.notebook_1_pane_1, -1, "Choose")
        self.updateButton = wx.Button(self.notebook_1_pane_1, -1, "UPDATE")
        self.label_1 = wx.StaticText(self.notebook_1_pane_1, -1, "Current # scan")
        self.nScanBox = wx.TextCtrl(self.notebook_1_pane_1, -1, "", style=wx.TE_READONLY)
        self.label_2 = wx.StaticText(self.notebook_1_pane_1, -1, "Scan No.")
        self.chooseScanBox1 = wx.TextCtrl(self.notebook_1_pane_1, -1, "")
        self.ffflabel = wx.StaticText(self.notebook_1_pane_1, -1, "Point")
        self.choosePoint1 = wx.TextCtrl(self.notebook_1_pane_1, -1, "")
        self.chooseButton1 = wx.Button(self.notebook_1_pane_1, -1, "Choose Scan")
        self.label_2_copy = wx.StaticText(self.notebook_1_pane_1, -1, "Scan No.")
        self.chooseScanBox2 = wx.TextCtrl(self.notebook_1_pane_1, -1, "")
        self.ffflabel_copy = wx.StaticText(self.notebook_1_pane_1, -1, "Point")
        self.choosePoint2 = wx.TextCtrl(self.notebook_1_pane_1, -1, "")
        self.chooseButton2 = wx.Button(self.notebook_1_pane_1, -1, "Choose Scan")
        self.list_ctrl_1 = wx.ListCtrl(self.notebook_1_pane_1, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.list_ctrl_2 = wx.ListCtrl(self.notebook_1_pane_1, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.pushChoose, self.button_1_copy)
        self.Bind(wx.EVT_BUTTON, self.pushUpdate, self.updateButton)
        self.Bind(wx.EVT_BUTTON, self.pushChoose1, self.chooseButton1)
        self.Bind(wx.EVT_BUTTON, self.pushChoose2, self.chooseButton2)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame_1")
        self.label_4.SetMinSize((100, 18))
        self.label_4.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.filenameBox.SetMinSize((350, 24))
        self.updateButton.SetMinSize((85, 27))
        self.nScanBox.SetBackgroundColour(wx.Colour(192, 192, 192))
        self.label_2.SetMinSize((57, 17))
        self.list_ctrl_1.SetMinSize((300, 400))
        self.list_ctrl_2.SetMinSize((300,400))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_5_copy_1, 0, wx.ALL|wx.EXPAND, 0)
        sizer_6.Add(self.label_4, 0, 0, 0)
        sizer_6.Add(self.filenameBox, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_6.Add(self.button_1_copy, 0, 0, 0)
        sizer_2.Add(sizer_6, 0, wx.EXPAND, 0)
        sizer_5.Add(self.updateButton, 0, 0, 0)
        sizer_5.Add((20, 20), 0, 0, 0)
        sizer_5.Add(self.label_1, 0, 0, 0)
        sizer_5.Add(self.nScanBox, 0, 0, 0)
        sizer_2.Add(sizer_5, 0, wx.EXPAND, 0)
        sizer_7.Add(self.label_2, 0, 0, 0)
        sizer_7.Add(self.chooseScanBox1, 0, 0, 0)
        sizer_7.Add(self.ffflabel, 0, 0, 0)
        sizer_7.Add(self.choosePoint1, 0, 0, 0)
        sizer_7.Add(self.chooseButton1, 0, 0, 0)
        sizer_7.Add((50, 20), 0, 0, 0)
        sizer_7.Add(self.label_2_copy, 0, 0, 0)
        sizer_7.Add(self.chooseScanBox2, 0, 0, 0)
        sizer_7.Add(self.ffflabel_copy, 0, 0, 0)
        sizer_7.Add(self.choosePoint2, 0, 0, 0)
        sizer_7.Add(self.chooseButton2, 0, 0, 0)
        sizer_2.Add(sizer_7, 0, wx.EXPAND, 0)
        sizer_3.Add(self.list_ctrl_1, 1, wx.EXPAND, 0)
        sizer_3.Add(self.list_ctrl_2, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        self.notebook_1_pane_1.SetSizer(sizer_2)
        self.notebook_1.AddPage(self.notebook_1_pane_1, "Scanner")
        sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        self.Centre()
        # end wxGlade

    def pushChoose(self, event): # wxGlade: MyFrame.<event_handler>
        self.dirName = ''
        dialog = wx.FileDialog(self, "Choose a file", self.dirName, "", "*.*", wx.OPEN)
        if dialog.ShowModal() == wx.ID_OK:
            self.fileName = dialog.GetFilename()
            self.dirName = dialog.GetDirectory()
            print self.fileName,self.dirName
            self.logfile="%s/%s"%(self.dirName,self.fileName)
            self.filenameBox.SetValue(self.logfile)
        dialog.Destroy()

    def setList(self):
	nlist=int(self.nScanBox.GetValue())
	print nlist
	for i in range(0,nlist):
        	self.list_ctrl_1.InsertStringItem(0,"TEST")

    def pushUpdate(self, event): # wxGlade: MyFrame.<event_handler>
	self.dsl=DiffscanLog(self.logfile)
	self.nscan=self.dsl.prep()
        self.nScanBox.SetValue("%d"%self.nscan)
	#self.setList()

    def pushChoose1(self, event): # wxGlade: MyFrame.<event_handler>
	# Scan No
	nscan=int(self.chooseScanBox1.GetValue())
	# Point No
	npoint=int(self.choosePoint1.GetValue())
	# Test
	print self.dsl.getPosition(nscan,npoint)

    def pushChoose2(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `pushChoose2' not implemented"
        event.Skip()

# end of class MyFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
