#!/usr/bin/env python
# -*- coding: ansi_x3.4-1968 -*-
# generated by wxGlade 0.6.3 on Tue May  8 23:23:07 2012

import wx
from wxPython.wx import *

# begin wxGlade: extracode
# end wxGlade



class OhMyGod(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: OhMyGod.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.button_1 = wx.Button(self, -1, "button_1")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.pushy, self.button_1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: OhMyGod.__set_properties
        self.SetTitle("frame_1")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: OhMyGod.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.button_1, 0, 0, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def pushy(self, event): # wxGlade: OhMyGod.<event_handler>
	# Create a save file dialog
	dialog = wxFileDialog ( None, style = wxSAVE )
	# Show the dialog and get user input
	if dialog.ShowModal() == wxID_OK:
   		print 'Selected:', dialog.GetPath()
		# The user did not select anything
	else:
   		print 'Nothing was selected.'
		# Destroy the dialog
	dialog.Destroy()

# end of class OhMyGod


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = OhMyGod(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
