#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sat Jul  3 17:55:37 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.sizer_4_staticbox = wx.StaticBox(self, -1, "List")
        self.sizer_3_staticbox = wx.StaticBox(self, -1, "Action")
        
        # Menu Bar
        self.frame_1_menubar = wx.MenuBar()
        self.File = wx.Menu()
        self.Exit = wx.MenuItem(self.File, wx.NewId(), "Exit", "", wx.ITEM_NORMAL)
        self.File.AppendItem(self.Exit)
        self.frame_1_menubar.Append(self.File, "File")
        self.Sort = wx.Menu()
        self.SortList1 = wx.MenuItem(self.Sort, wx.NewId(), "SortList1", "", wx.ITEM_NORMAL)
        self.Sort.AppendItem(self.SortList1)
        self.frame_1_menubar.Append(self.Sort, "Sort")
        self.SetMenuBar(self.frame_1_menubar)
        # Menu Bar end
        self.appendButton = wx.Button(self, -1, "Append")
        self.deleteButton = wx.Button(self, -1, "Delete")
        self.clearAllButton = wx.Button(self, -1, "Clear All")
        self.ExitButton = wx.Button(self, -1, "Exit")
        self.label_1 = wx.StaticText(self, -1, "Comment")
        self.inputComment = wx.TextCtrl(self, -1, "")
        self.text1 = wx.StaticText(self, -1, "Do")
        self.doCentering = wx.Button(self, -1, "Centering")
        self.label_3 = wx.StaticText(self, -1, "Current", style=wx.ALIGN_CENTRE)
        self.label_3_copy = wx.StaticText(self, -1, "Status", style=wx.ALIGN_CENTRE)
        self.label_4 = wx.StaticText(self, -1, "X[mm]")
        self.dispGonioX = wx.TextCtrl(self, -1, "")
        self.label_4_copy = wx.StaticText(self, -1, "Y[mm]")
        self.dispGonioY = wx.TextCtrl(self, -1, "")
        self.label_4_copy_1 = wx.StaticText(self, -1, "Z[mm]")
        self.dispGonioZ = wx.TextCtrl(self, -1, "")
        self.label_4_copy_2 = wx.StaticText(self, -1, "PHI[deg.]")
        self.dispPhi = wx.TextCtrl(self, -1, "")
        self.label_5 = wx.StaticText(self, -1, "Current status")
        self.button_1 = wx.Button(self, -1, "Update")
        self.list_ctrl_1 = wx.ListCtrl(self, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.label_2 = wx.StaticText(self, -1, "Action")
        self.moveButton = wx.Button(self, -1, "Move to the selected position")
        self.static_line_1 = wx.StaticLine(self, -1)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.OnSortList1, self.SortList1)
        self.Bind(wx.EVT_BUTTON, self.OnAppend, self.appendButton)
        self.Bind(wx.EVT_BUTTON, self.Ondelete, self.deleteButton)
        self.Bind(wx.EVT_BUTTON, self.OnClearAll, self.clearAllButton)
        self.Bind(wx.EVT_BUTTON, self.OnClose, self.ExitButton)
        self.Bind(wx.EVT_BUTTON, self.runCentering, self.doCentering)
        self.Bind(wx.EVT_BUTTON, self.update, self.button_1)
        self.Bind(wx.EVT_LIST_INSERT_ITEM, self.OnListInsertItem, self.list_ctrl_1)
        self.Bind(wx.EVT_LIST_ITEM_SELECTED, self.OnListSelected, self.list_ctrl_1)
        self.Bind(wx.EVT_LIST_ITEM_ACTIVATED, self.OnDobleClick, self.list_ctrl_1)
        self.Bind(wx.EVT_LIST_COL_CLICK, self.OnListColClick, self.list_ctrl_1)
        self.Bind(wx.EVT_BUTTON, self.pushMoveSele, self.moveButton)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame_1")
        self.inputComment.SetMinSize((250, 28))
        self.doCentering.SetMinSize((119, 40))
        self.dispGonioX.SetMinSize((80, 28))
        self.dispGonioY.SetMinSize((80, 28))
        self.dispGonioZ.SetMinSize((80, 28))
        self.dispPhi.SetMinSize((80, 28))
        self.button_1.SetMinSize((100, 32))
        self.list_ctrl_1.SetMinSize((100, 300))
        self.moveButton.SetMinSize((203, 32))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_13 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_14_copy_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_14_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_14 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.StaticBoxSizer(self.sizer_4_staticbox, wx.VERTICAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8_copy_copy_1_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_8_copy_copy_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_8_copy_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_8_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_8 = wx.BoxSizer(wx.VERTICAL)
        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.StaticBoxSizer(self.sizer_3_staticbox, wx.VERTICAL)
        sizer_3.Add(self.appendButton, 0, wx.ALL, 10)
        sizer_3.Add(self.deleteButton, 0, wx.ALL, 10)
        sizer_3.Add(self.clearAllButton, 0, wx.ALL, 10)
        sizer_3.Add(self.ExitButton, 0, wx.ALL, 10)
        sizer_3.Add((20, 10), 0, wx.ADJUST_MINSIZE, 0)
        sizer_2.Add(sizer_3, 0, wx.ALL|wx.EXPAND, 10)
        sizer_5.Add(self.label_1, 0, wx.ALL, 10)
        sizer_5.Add(self.inputComment, 0, wx.ALL, 10)
        sizer_5.Add(self.text1, 0, wx.ALL, 10)
        sizer_5.Add(self.doCentering, 0, wx.ALL|wx.ADJUST_MINSIZE, 0)
        sizer_4.Add(sizer_5, 0, 0, 0)
        sizer_9.Add(self.label_3, 0, wx.ADJUST_MINSIZE, 0)
        sizer_9.Add(self.label_3_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_7.Add(sizer_9, 1, wx.EXPAND, 0)
        sizer_7.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_8.Add(self.label_4, 0, wx.ADJUST_MINSIZE, 0)
        sizer_8.Add(self.dispGonioX, 0, wx.ADJUST_MINSIZE, 0)
        sizer_7.Add(sizer_8, 1, wx.EXPAND, 0)
        sizer_8_copy.Add(self.label_4_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_8_copy.Add(self.dispGonioY, 0, wx.ADJUST_MINSIZE, 0)
        sizer_7.Add(sizer_8_copy, 1, wx.EXPAND, 0)
        sizer_8_copy_copy.Add(self.label_4_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_8_copy_copy.Add(self.dispGonioZ, 0, wx.ADJUST_MINSIZE, 0)
        sizer_7.Add(sizer_8_copy_copy, 1, wx.EXPAND, 0)
        sizer_8_copy_copy_1.Add(self.label_4_copy_2, 0, wx.ADJUST_MINSIZE, 0)
        sizer_8_copy_copy_1.Add(self.dispPhi, 0, wx.ADJUST_MINSIZE, 0)
        sizer_7.Add(sizer_8_copy_copy_1, 1, wx.EXPAND, 0)
        sizer_8_copy_copy_1_copy.Add(self.label_5, 0, wx.ADJUST_MINSIZE, 0)
        sizer_8_copy_copy_1_copy.Add(self.button_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_7.Add(sizer_8_copy_copy_1_copy, 1, wx.EXPAND, 0)
        sizer_4.Add(sizer_7, 1, wx.EXPAND, 0)
        sizer_4.Add(self.list_ctrl_1, 3, wx.ALL|wx.EXPAND, 10)
        sizer_10.Add(self.label_2, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10.Add((200, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_10.Add(self.moveButton, 0, wx.ADJUST_MINSIZE, 0)
        sizer_4.Add(sizer_10, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_4, 1, wx.ALL|wx.EXPAND, 10)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        sizer_1.Add(self.static_line_1, 0, wx.EXPAND, 0)
        sizer_14.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_14.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_14.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_14.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_13.Add(sizer_14, 1, wx.EXPAND, 0)
        sizer_14_copy.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_14_copy.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_14_copy.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_14_copy.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_13.Add(sizer_14_copy, 1, wx.EXPAND, 0)
        sizer_14_copy_1.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_14_copy_1.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_14_copy_1.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_14_copy_1.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_13.Add(sizer_14_copy_1, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_13, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def OnSortList1(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `OnSortList1' not implemented!"
        event.Skip()

    def OnAppend(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `OnAppend' not implemented!"
        event.Skip()

    def Ondelete(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `Ondelete' not implemented!"
        event.Skip()

    def OnClearAll(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `OnClearAll' not implemented!"
        event.Skip()

    def OnClose(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `OnClose' not implemented!"
        event.Skip()

    def runCentering(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `runCentering' not implemented!"
        event.Skip()

    def update(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `update' not implemented!"
        event.Skip()

    def OnListInsertItem(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `OnListInsertItem' not implemented!"
        event.Skip()

    def OnListSelected(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `OnListSelected' not implemented!"
        event.Skip()

    def OnDobleClick(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `OnDobleClick' not implemented!"
        event.Skip()

    def OnListColClick(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `OnListColClick' not implemented!"
        event.Skip()

    def pushMoveSele(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `pushMoveSele' not implemented!"
        event.Skip()

# end of class MyFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    GonioList = MyFrame(None, -1, "")
    app.SetTopWindow(GonioList)
    GonioList.Show()
    app.MainLoop()
